In [1]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import yfinance as yf
import talib
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from torch.utils.data import Dataset, DataLoader, Subset
from sklearn.model_selection import train_test_split
import torch.optim as optim
import os
from sklearn.model_selection import TimeSeriesSplit

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, log_loss, mean_absolute_error, mean_squared_error, r2_score, mean_absolute_percentage_error
import matplotlib.pyplot as plt
import scipy.cluster.hierarchy as sch
import seaborn as sns

import optuna
from optuna.samplers import TPESampler
from optuna.trial import TrialState
from torch.optim.lr_scheduler import StepLR, ReduceLROnPlateau 
import shap
import plotly.graph_objs as go
import plotly.offline as pyo
from tqdm.auto import tqdm
from sklearn.utils.class_weight import compute_class_weight

In [2]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    print("gpu")
else:
    device = torch.device('cpu')
print(torch.__version__)
print('CUDA available:', torch.cuda.is_available())
print('CUDA version:', torch.version.cuda)
print('cuDNN version:', torch.backends.cudnn.version())

gpu
2.1.2+cu121
CUDA available: True
CUDA version: 12.1
cuDNN version: 8902

In [3]:
start_date = '2018-01-01'
end_date = '2024-01-24'

stock_data = yf.download("AAPL", start=start_date, end=end_date)[["Adj Close", "High", "Low", "Volume"]]

stock_data = stock_data.reset_index()

stock_data = stock_data[['Date', 'Adj Close', "High", "Low", "Volume"]]

stock_data = stock_data.sort_values(by="Date")
stock_data.head(45)

[*********************100%%**********************]  1 of 1 completed

         Date  Adj Close       High        Low     Volume
0  2018-01-02  40.722874  43.075001  42.314999  102223600
1  2018-01-03  40.715786  43.637501  42.990002  118071600
2  2018-01-04  40.904907  43.367500  43.020000   89738400
3  2018-01-05  41.370625  43.842499  43.262501   94640000
4  2018-01-08  41.216969  43.902500  43.482498   82271200
5  2018-01-09  41.212234  43.764999  43.352501   86336000
6  2018-01-10  41.202766  43.575001  43.250000   95839600
7  2018-01-11  41.436813  43.872501  43.622501   74670800
8  2018-01-12  41.864708  44.340000  43.912498  101672400
9  2018-01-16  41.651943  44.847500  44.035000  118263600
10 2018-01-17  42.339878  44.812500  43.767502  137547200
11 2018-01-18  42.377693  45.025002  44.562500  124773600
12 2018-01-19  42.188583  44.895000  44.352501  129700400
13 2018-01-22  41.843433  44.445000  44.150002  108434400
14 2018-01-23  41.852879  44.860001  44.205002  130756400
15 2018-01-24  41.186226  44.325001  43.299999  204420400
16 2018-01-25  40.451015  43.737499  42.632500  166116000
17 2018-01-26  40.545567  43.000000  42.514999  156572000
18 2018-01-29  39.706337  42.540001  41.767502  202561600
19 2018-01-30  39.472294  41.842499  41.174999  184192800
20 2018-01-31  39.581047  42.110001  41.625000  129915600
21 2018-02-01  39.663788  42.154999  41.689999  188923200
22 2018-02-02  37.942768  41.700001  40.025002  346375200
23 2018-02-05  36.994801  40.970001  39.000000  290954000
24 2018-02-06  38.540863  40.930000  38.500000  272975200
25 2018-02-07  37.715813  40.849998  39.767502  206434400
26 2018-02-08  36.678005  40.250000  38.757500  217562000
27 2018-02-09  37.126640  39.472500  37.560001  282690400
28 2018-02-12  38.622051  40.972500  39.377499  243278000
29 2018-02-13  39.008961  41.187500  40.412498  130196800
30 2018-02-14  39.728184  41.884998  40.720001  162579600
31 2018-02-15  41.062191  43.272499  42.250000  204588800
32 2018-02-16  40.929253  43.705002  42.942501  160704400
33 2018-02-20  40.791584  43.564999  42.855000  135722000
34 2018-02-21  40.606445  43.529999  42.752499  149886400
35 2018-02-22  40.945881  43.487499  42.927502  123967600
36 2018-02-23  41.657982  43.912498  43.384998  135249600
37 2018-02-26  42.481632  44.847500  44.052502  152648800
38 2018-02-27  42.343975  45.119999  44.540001  155712400
39 2018-02-28  42.279884  45.154999  44.512501  151128400
40 2018-03-01  41.539303  44.945000  43.165001  195208000
41 2018-03-02  41.826515  44.075001  43.112499  153816000
42 2018-03-05  41.971302  44.435001  43.630001  113605600
43 2018-03-06  41.935707  44.562500  44.032501   95154000
44 2018-03-07  41.546413  43.962502  43.567501  126814000

In [4]:
time_step = 44

In [5]:
test_index = int((len(stock_data)-44)*0.8+44+44)

In [6]:
date = stock_data["Date"].iloc[time_step:].dt.strftime('%Y-%m-%d')
date_test = stock_data["Date"].iloc[test_index:].reset_index()
date_test.drop(columns=["index"], inplace=True)
date_test

          Date
0   2023-01-23
1   2023-01-24
2   2023-01-25
3   2023-01-26
4   2023-01-27
..         ...
247 2024-01-17
248 2024-01-18
249 2024-01-19
250 2024-01-22
251 2024-01-23

[252 rows x 1 columns]

In [7]:
def add_technical_indicators(data, timeperiod=time_step):

    # MACD
    macd, macdsignal, macdhist = talib.MACD(data["Adj Close"], fastperiod=12, slowperiod=26, signalperiod=9)

    rsi = talib.RSI(data["Adj Close"], timeperiod=14)

    # CMO
    cmo = talib.CMO(data["Adj Close"], timeperiod=timeperiod)

    # MOM
    mom = talib.MOM(data["Adj Close"], timeperiod=timeperiod)

    # Bollinger Bands
    upperband, middleband, lowerband = talib.BBANDS(data["Adj Close"], timeperiod=20, nbdevup=2, nbdevdn=2, matype=0)

    # SMA
    sma_s = talib.SMA(data["Adj Close"], timeperiod=20)
    sma_l = talib.SMA(data["Adj Close"], timeperiod=50)

    # Calculate Exponential Moving Average (EMA)
    ema = talib.EMA(data["Adj Close"], timeperiod=timeperiod)

    # Calculate Stochastic Oscillator
    slowk, slowd = talib.STOCH(data['High'], data['Low'], data['Adj Close'], fastk_period=14, slowk_period=3, slowk_matype=0, slowd_period=3, slowd_matype=0)

    # Calculate Average True Range (ATR)
    atr = talib.ATR(data['High'], data['Low'], data['Adj Close'], timeperiod=14)

    # Calculate On-Balance Volume (OBV)
    obv = talib.OBV(data['Adj Close'], data['Volume'])

    # Combine all indicators into a DataFrame
    indicators = pd.DataFrame({
        'MACD': macd,
        'MACD_signal': macdsignal,
        'RSI': rsi,
        'CMO': cmo,
        'MOM': mom,
        'Upper_BB': upperband,
        'Middle_BB': middleband,
        'Lower_BB': lowerband,
        'SMA_SHORT': sma_s,
        'SMA_LONG': sma_l,
        'EMA': ema,
        'SLOWK': slowk,
        'SLOWD': slowd,
        'ATR': atr,
        'OBV': obv,

    })
    return indicators

In [8]:
indicators = add_technical_indicators(stock_data)
indicators.head(45)

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102223600.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-15848000.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73890400.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168530400.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86259200.0
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-76800.0
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-95916400.0
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-21245600.0
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80426800.0
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-37836800.0
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99710400.0
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,224484000.0
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94783600.0
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13650800.0
14,NaN,NaN,68.998412,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.724164,117105600.0
15,NaN,NaN,55.580779,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.706161,-87314800.0
16,NaN,NaN,45.152447,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.695097,-253430800.0
17,NaN,NaN,46.541587,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-87.034489,-73.817896,2.684661,-96858800.0
18,NaN,NaN,37.470203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-77.639294,-81.393301,2.635359,-299420400.0
19,NaN,NaN,35.398096,NaN,NaN,42.761513,41.213177,39.664840,41.213177,NaN,NaN,-61.987975,-75.553919,2.599702,-483613200.0
20,NaN,NaN,37.137688,NaN,NaN,42.849897,41.156085,39.462273,41.156085,NaN,NaN,-49.633954,-63.087074,2.602416,-353697600.0
21,NaN,NaN,38.494678,NaN,NaN,42.910292,41.103485,39.296679,41.103485,NaN,NaN,-41.626546,-51.082825,2.600383,-164774400.0
22,NaN,NaN,25.947756,NaN,NaN,43.228470,40.955378,38.682286,40.955378,NaN,NaN,-40.766073,-44.008858,2.560085,-511149600.0
23,NaN,NaN,21.743751,NaN,NaN,43.578808,40.736587,37.894367,40.736587,NaN,NaN,-38.059400,-40.150673,2.593453,-802103600.0
24,NaN,NaN,39.079579,NaN,NaN,43.590204,40.602782,37.615360,40.602782,NaN,NaN,-24.766575,-34.530683,2.689292,-529128400.0
25,NaN,NaN,34.666212,NaN,NaN,43.652100,40.427961,37.203822,40.427961,NaN,NaN,-14.972521,-25.932832,2.662138,-735562800.0
26,NaN,NaN,30.066560,NaN,NaN,43.790971,40.201723,36.612474,40.201723,NaN,NaN,-13.427989,-17.722362,2.652999,-953124800.0
27,NaN,NaN,34.135058,NaN,NaN,43.765509,39.986214,36.206920,39.986214,NaN,NaN,-15.615558,-14.672023,2.663106,-670434400.0
28,NaN,NaN,45.513656,NaN,NaN,43.544882,39.824081,36.103280,39.824081,NaN,NaN,-6.294994,-11.779513,2.747588,-427156400.0
29,NaN,NaN,48.015949,NaN,NaN,43.330500,39.691932,36.053365,39.691932,NaN,NaN,11.072725,-3.612609,2.734578,-296959600.0
30,NaN,NaN,52.392802,NaN,NaN,42.991931,39.561347,36.130764,39.561347,NaN,NaN,26.336977,10.371569,2.744682,-134380000.0
31,NaN,NaN,59.246649,NaN,NaN,42.753753,39.495572,36.237391,39.495572,NaN,NaN,41.539749,26.316483,2.801799,70208800.0
32,NaN,NaN,58.345195,NaN,NaN,42.524613,39.432606,36.340598,39.432606,NaN,NaN,51.997650,39.958125,2.790443,-90495600.0
33,-0.373864,-0.940886,57.371671,NaN,NaN,42.339134,39.380013,36.420893,39.380013,NaN,NaN,56.241819,49.926406,2.779393,-226217600.0
34,-0.274210,-0.807551,56.017990,NaN,NaN,42.113880,39.317692,36.521503,39.317692,NaN,NaN,52.331311,53.523593,2.776466,-376104000.0
35,-0.165930,-0.679226,57.975768,NaN,NaN,42.071540,39.305674,36.539809,39.305674,NaN,NaN,52.421510,53.664880,2.783936,-252136400.0
36,-0.022399,-0.547861,61.815847,NaN,NaN,42.278024,39.366023,36.454021,39.366023,NaN,NaN,56.395159,53.715993,2.796985,-116886800.0
37,0.156014,-0.407086,65.717906,NaN,NaN,42.641726,39.462826,36.283926,39.462826,NaN,NaN,62.381586,57.066085,2.825023,35762000.0
38,0.283037,-0.269061,64.530991,NaN,NaN,43.012921,39.594708,36.176495,39.594708,NaN,NaN,65.108370,61.295039,2.811691,-119950400.0
39,0.374218,-0.140405,63.951869,NaN,NaN,43.346790,39.735087,36.123385,39.735087,NaN,NaN,64.319994,63.936650,2.811643,-271078800.0
40,0.382314,-0.035861,57.527377,NaN,NaN,43.527907,39.833000,36.138093,39.833000,NaN,NaN,59.272814,62.900393,2.801177,-466286800.0
41,0.407212,0.052753,59.237629,NaN,NaN,43.735166,39.941137,36.147107,39.941137,NaN,NaN,52.309069,58.633959,2.782214,-312470800.0
42,0.433628,0.128928,60.109654,NaN,NaN,43.918538,40.142563,36.366588,40.142563,NaN,NaN,42.550464,51.377449,2.769805,-198865200.0
43,0.446543,0.192451,59.771118,NaN,NaN,43.949841,40.389609,36.829377,40.389609,NaN,40.596321,34.223107,43.027547,2.757047,-294019200.0
44,0.420519,0.238065,56.052918,4.051384,0.82354,44.028293,40.539886,37.051479,40.539886,NaN,40.638547,12.020201,29.597924,2.704886,-420833200.0

In [9]:
indicators_with_price = pd.concat([indicators, stock_data["Adj Close"]], axis=1, join='inner')
indicators_with_price.head(45)

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102223600.0,40.722874
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-15848000.0,40.715786
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73890400.0,40.904907
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168530400.0,41.370625
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86259200.0,41.216969
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-76800.0,41.212234
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-95916400.0,41.202766
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-21245600.0,41.436813
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80426800.0,41.864708
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-37836800.0,41.651943
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99710400.0,42.339878
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,224484000.0,42.377693
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94783600.0,42.188583
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13650800.0,41.843433
14,NaN,NaN,68.998412,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.724164,117105600.0,41.852879
15,NaN,NaN,55.580779,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.706161,-87314800.0,41.186226
16,NaN,NaN,45.152447,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.695097,-253430800.0,40.451015
17,NaN,NaN,46.541587,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-87.034489,-73.817896,2.684661,-96858800.0,40.545567
18,NaN,NaN,37.470203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-77.639294,-81.393301,2.635359,-299420400.0,39.706337
19,NaN,NaN,35.398096,NaN,NaN,42.761513,41.213177,39.664840,41.213177,NaN,NaN,-61.987975,-75.553919,2.599702,-483613200.0,39.472294
20,NaN,NaN,37.137688,NaN,NaN,42.849897,41.156085,39.462273,41.156085,NaN,NaN,-49.633954,-63.087074,2.602416,-353697600.0,39.581047
21,NaN,NaN,38.494678,NaN,NaN,42.910292,41.103485,39.296679,41.103485,NaN,NaN,-41.626546,-51.082825,2.600383,-164774400.0,39.663788
22,NaN,NaN,25.947756,NaN,NaN,43.228470,40.955378,38.682286,40.955378,NaN,NaN,-40.766073,-44.008858,2.560085,-511149600.0,37.942768
23,NaN,NaN,21.743751,NaN,NaN,43.578808,40.736587,37.894367,40.736587,NaN,NaN,-38.059400,-40.150673,2.593453,-802103600.0,36.994801
24,NaN,NaN,39.079579,NaN,NaN,43.590204,40.602782,37.615360,40.602782,NaN,NaN,-24.766575,-34.530683,2.689292,-529128400.0,38.540863
25,NaN,NaN,34.666212,NaN,NaN,43.652100,40.427961,37.203822,40.427961,NaN,NaN,-14.972521,-25.932832,2.662138,-735562800.0,37.715813
26,NaN,NaN,30.066560,NaN,NaN,43.790971,40.201723,36.612474,40.201723,NaN,NaN,-13.427989,-17.722362,2.652999,-953124800.0,36.678005
27,NaN,NaN,34.135058,NaN,NaN,43.765509,39.986214,36.206920,39.986214,NaN,NaN,-15.615558,-14.672023,2.663106,-670434400.0,37.126640
28,NaN,NaN,45.513656,NaN,NaN,43.544882,39.824081,36.103280,39.824081,NaN,NaN,-6.294994,-11.779513,2.747588,-427156400.0,38.622051
29,NaN,NaN,48.015949,NaN,NaN,43.330500,39.691932,36.053365,39.691932,NaN,NaN,11.072725,-3.612609,2.734578,-296959600.0,39.008961
30,NaN,NaN,52.392802,NaN,NaN,42.991931,39.561347,36.130764,39.561347,NaN,NaN,26.336977,10.371569,2.744682,-134380000.0,39.728184
31,NaN,NaN,59.246649,NaN,NaN,42.753753,39.495572,36.237391,39.495572,NaN,NaN,41.539749,26.316483,2.801799,70208800.0,41.062191
32,NaN,NaN,58.345195,NaN,NaN,42.524613,39.432606,36.340598,39.432606,NaN,NaN,51.997650,39.958125,2.790443,-90495600.0,40.929253
33,-0.373864,-0.940886,57.371671,NaN,NaN,42.339134,39.380013,36.420893,39.380013,NaN,NaN,56.241819,49.926406,2.779393,-226217600.0,40.791584
34,-0.274210,-0.807551,56.017990,NaN,NaN,42.113880,39.317692,36.521503,39.317692,NaN,NaN,52.331311,53.523593,2.776466,-376104000.0,40.606445
35,-0.165930,-0.679226,57.975768,NaN,NaN,42.071540,39.305674,36.539809,39.305674,NaN,NaN,52.421510,53.664880,2.783936,-252136400.0,40.945881
36,-0.022399,-0.547861,61.815847,NaN,NaN,42.278024,39.366023,36.454021,39.366023,NaN,NaN,56.395159,53.715993,2.796985,-116886800.0,41.657982
37,0.156014,-0.407086,65.717906,NaN,NaN,42.641726,39.462826,36.283926,39.462826,NaN,NaN,62.381586,57.066085,2.825023,35762000.0,42.481632
38,0.283037,-0.269061,64.530991,NaN,NaN,43.012921,39.594708,36.176495,39.594708,NaN,NaN,65.108370,61.295039,2.811691,-119950400.0,42.343975
39,0.374218,-0.140405,63.951869,NaN,NaN,43.346790,39.735087,36.123385,39.735087,NaN,NaN,64.319994,63.936650,2.811643,-271078800.0,42.279884
40,0.382314,-0.035861,57.527377,NaN,NaN,43.527907,39.833000,36.138093,39.833000,NaN,NaN,59.272814,62.900393,2.801177,-466286800.0,41.539303
41,0.407212,0.052753,59.237629,NaN,NaN,43.735166,39.941137,36.147107,39.941137,NaN,NaN,52.309069,58.633959,2.782214,-312470800.0,41.826515
42,0.433628,0.128928,60.109654,NaN,NaN,43.918538,40.142563,36.366588,40.142563,NaN,NaN,42.550464,51.377449,2.769805,-198865200.0,41.971302
43,0.446543,0.192451,59.771118,NaN,NaN,43.949841,40.389609,36.829377,40.389609,NaN,40.596321,34.223107,43.027547,2.757047,-294019200.0,41.935707
44,0.420519,0.238065,56.052918,4.051384,0.82354,44.028293,40.539886,37.051479,40.539886,NaN,40.638547,12.020201,29.597924,2.704886,-420833200.0,41.546413

In [10]:
indicators_with_price = indicators_with_price.dropna()
indicators_with_price = indicators_with_price.reset_index(drop=True)
indicators_with_price

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close
0,0.567014,0.443929,58.241688,7.100914,1.143612,43.382886,41.728834,40.074782,41.728834,40.814299,41.035721,-7.013324,-3.909678,2.715222,-3.124152e+08,42.355846
1,0.548494,0.464842,58.592203,7.332889,1.202915,43.261030,41.862709,40.464387,41.862709,40.847955,41.096608,-20.016565,-8.448297,2.714432,-2.214400e+08,42.405682
2,0.515805,0.475034,57.044786,6.516171,0.819321,43.280286,41.922406,40.564526,41.922406,40.878762,41.148142,-27.991976,-18.340622,2.690138,-3.790588e+08,42.256134
3,0.432811,0.466590,50.806368,3.052120,-0.254204,43.245415,41.956468,40.667522,41.956468,40.892874,41.168692,-36.985545,-28.331362,2.648797,-5.128460e+08,41.610504
4,0.361721,0.445616,50.674804,2.976578,-0.055672,43.183912,41.996703,40.809494,41.996703,40.897387,41.187695,-46.752180,-37.243234,2.644561,-5.914436e+08,41.596272
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1470,-1.918426,-1.197745,36.736038,-3.771153,-3.720001,199.131030,188.796999,178.462968,188.796999,189.292038,187.549134,26.310155,30.750307,3.101382,3.547580e+09,182.679993
1471,-1.555397,-1.269276,51.604604,4.598480,3.830002,198.242596,188.434000,178.625403,188.434000,189.536287,187.597173,33.195313,30.241850,3.341284,3.625586e+09,188.630005
1472,-1.019515,-1.219324,56.967975,8.324259,4.119995,197.297528,188.164999,179.032471,188.164999,189.787603,187.773298,51.916516,37.140661,3.339763,3.694327e+09,191.559998
1473,-0.402178,-1.055894,60.698088,11.147862,5.880005,197.121605,188.117999,179.114394,188.117999,190.033787,188.045152,76.309536,53.807122,3.370495,3.754460e+09,193.889999
1474,0.188980,-0.806919,62.629499,12.671634,5.469986,197.221811,188.142999,179.064188,188.142999,190.284400,188.362256,88.961635,72.395896,3.266888,3.796816e+09,195.179993

In [11]:
indicators_with_price['Prev_Adj_Close'] = indicators_with_price['Adj Close'].shift(1)
indicators_with_price['Return'] = ((indicators_with_price['Adj Close'] - indicators_with_price['Prev_Adj_Close'])/indicators_with_price['Prev_Adj_Close'])*100
indicators_with_price['Signal'] = np.where(indicators_with_price['Return'] > 1, 1,
                                           np.where(indicators_with_price['Return'] < -1, 2, 0))
indicators_with_price

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close,Prev_Adj_Close,Return,Signal
0,0.567014,0.443929,58.241688,7.100914,1.143612,43.382886,41.728834,40.074782,41.728834,40.814299,41.035721,-7.013324,-3.909678,2.715222,-3.124152e+08,42.355846,NaN,NaN,0
1,0.548494,0.464842,58.592203,7.332889,1.202915,43.261030,41.862709,40.464387,41.862709,40.847955,41.096608,-20.016565,-8.448297,2.714432,-2.214400e+08,42.405682,42.355846,0.117658,0
2,0.515805,0.475034,57.044786,6.516171,0.819321,43.280286,41.922406,40.564526,41.922406,40.878762,41.148142,-27.991976,-18.340622,2.690138,-3.790588e+08,42.256134,42.405682,-0.352659,0
3,0.432811,0.466590,50.806368,3.052120,-0.254204,43.245415,41.956468,40.667522,41.956468,40.892874,41.168692,-36.985545,-28.331362,2.648797,-5.128460e+08,41.610504,42.256134,-1.527896,2
4,0.361721,0.445616,50.674804,2.976578,-0.055672,43.183912,41.996703,40.809494,41.996703,40.897387,41.187695,-46.752180,-37.243234,2.644561,-5.914436e+08,41.596272,41.610504,-0.034204,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1470,-1.918426,-1.197745,36.736038,-3.771153,-3.720001,199.131030,188.796999,178.462968,188.796999,189.292038,187.549134,26.310155,30.750307,3.101382,3.547580e+09,182.679993,183.630005,-0.517351,0
1471,-1.555397,-1.269276,51.604604,4.598480,3.830002,198.242596,188.434000,178.625403,188.434000,189.536287,187.597173,33.195313,30.241850,3.341284,3.625586e+09,188.630005,182.679993,3.257068,1
1472,-1.019515,-1.219324,56.967975,8.324259,4.119995,197.297528,188.164999,179.032471,188.164999,189.787603,187.773298,51.916516,37.140661,3.339763,3.694327e+09,191.559998,188.630005,1.553301,1
1473,-0.402178,-1.055894,60.698088,11.147862,5.880005,197.121605,188.117999,179.114394,188.117999,190.033787,188.045152,76.309536,53.807122,3.370495,3.754460e+09,193.889999,191.559998,1.216330,1
1474,0.188980,-0.806919,62.629499,12.671634,5.469986,197.221811,188.142999,179.064188,188.142999,190.284400,188.362256,88.961635,72.395896,3.266888,3.796816e+09,195.179993,193.889999,0.665322,0

In [12]:
indicators_with_price["Signal"].value_counts()

Signal
0    737
1    414
2    324
Name: count, dtype: int64

In [13]:
indicators_with_price.dropna(inplace=True)
indicators_with_price

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close,Prev_Adj_Close,Return,Signal
1,0.548494,0.464842,58.592203,7.332889,1.202915,43.261030,41.862709,40.464387,41.862709,40.847955,41.096608,-20.016565,-8.448297,2.714432,-2.214400e+08,42.405682,42.355846,0.117658,0
2,0.515805,0.475034,57.044786,6.516171,0.819321,43.280286,41.922406,40.564526,41.922406,40.878762,41.148142,-27.991976,-18.340622,2.690138,-3.790588e+08,42.256134,42.405682,-0.352659,0
3,0.432811,0.466590,50.806368,3.052120,-0.254204,43.245415,41.956468,40.667522,41.956468,40.892874,41.168692,-36.985545,-28.331362,2.648797,-5.128460e+08,41.610504,42.256134,-1.527896,2
4,0.361721,0.445616,50.674804,2.976578,-0.055672,43.183912,41.996703,40.809494,41.996703,40.897387,41.187695,-46.752180,-37.243234,2.644561,-5.914436e+08,41.596272,41.610504,-0.034204,0
5,0.226727,0.401838,42.776429,-1.895766,-1.685963,43.175297,41.999076,40.822855,41.999076,40.886126,41.163972,-59.960169,-47.899298,2.611109,-7.396632e+08,40.653915,41.596272,-2.265482,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1470,-1.918426,-1.197745,36.736038,-3.771153,-3.720001,199.131030,188.796999,178.462968,188.796999,189.292038,187.549134,26.310155,30.750307,3.101382,3.547580e+09,182.679993,183.630005,-0.517351,0
1471,-1.555397,-1.269276,51.604604,4.598480,3.830002,198.242596,188.434000,178.625403,188.434000,189.536287,187.597173,33.195313,30.241850,3.341284,3.625586e+09,188.630005,182.679993,3.257068,1
1472,-1.019515,-1.219324,56.967975,8.324259,4.119995,197.297528,188.164999,179.032471,188.164999,189.787603,187.773298,51.916516,37.140661,3.339763,3.694327e+09,191.559998,188.630005,1.553301,1
1473,-0.402178,-1.055894,60.698088,11.147862,5.880005,197.121605,188.117999,179.114394,188.117999,190.033787,188.045152,76.309536,53.807122,3.370495,3.754460e+09,193.889999,191.559998,1.216330,1
1474,0.188980,-0.806919,62.629499,12.671634,5.469986,197.221811,188.142999,179.064188,188.142999,190.284400,188.362256,88.961635,72.395896,3.266888,3.796816e+09,195.179993,193.889999,0.665322,0

In [14]:
indicators_with_price.columns

Index(['MACD', 'MACD_signal', 'RSI', 'CMO', 'MOM', 'Upper_BB', 'Middle_BB',
       'Lower_BB', 'SMA_SHORT', 'SMA_LONG', 'EMA', 'SLOWK', 'SLOWD', 'ATR',
       'OBV', 'Adj Close', 'Prev_Adj_Close', 'Return', 'Signal'],
      dtype='object')

In [15]:
# indicators_with_price = indicators_with_price.drop(columns=['Next_Adj_Close', 'Return'])
# indicators_with_price

In [16]:
indicators_with_price.drop(columns=['Prev_Adj_Close', "Signal"], inplace=True)
indicators_with_price.head(50)

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close,Return
1,0.548494,0.464842,58.592203,7.332889,1.202915,43.261030,41.862709,40.464387,41.862709,40.847955,41.096608,-20.016565,-8.448297,2.714432,-2.214400e+08,42.405682,0.117658
2,0.515805,0.475034,57.044786,6.516171,0.819321,43.280286,41.922406,40.564526,41.922406,40.878762,41.148142,-27.991976,-18.340622,2.690138,-3.790588e+08,42.256134,-0.352659
3,0.432811,0.466590,50.806368,3.052120,-0.254204,43.245415,41.956468,40.667522,41.956468,40.892874,41.168692,-36.985545,-28.331362,2.648797,-5.128460e+08,41.610504,-1.527896
4,0.361721,0.445616,50.674804,2.976578,-0.055672,43.183912,41.996703,40.809494,41.996703,40.897387,41.187695,-46.752180,-37.243234,2.644561,-5.914436e+08,41.596272,-0.034204
5,0.226727,0.401838,42.776429,-1.895766,-1.685963,43.175297,41.999076,40.822855,41.999076,40.886126,41.163972,-59.960169,-47.899298,2.611109,-7.396632e+08,40.653915,-2.265482
6,0.072555,0.335982,38.805894,-4.708060,-2.298206,43.330933,41.955757,40.580580,41.955757,40.863471,41.115773,-60.364656,-55.692335,2.604321,-9.056264e+08,40.079487,-1.412972
7,-0.123099,0.244166,33.409929,-9.019951,-3.037209,43.669844,41.830426,39.991009,41.830426,40.822443,41.028466,-57.037882,-59.120902,2.589764,-1.069742e+09,39.151375,-2.315678
8,-0.126721,0.169988,48.771984,0.230820,-0.833458,43.603899,41.756843,39.909788,41.756843,40.813906,41.027644,-35.113242,-50.838593,2.699325,-9.195768e+08,41.009975,4.747217
9,-0.212000,0.093591,42.761366,-4.462427,-1.894451,43.620649,41.637566,39.654483,41.637566,40.775781,40.980123,-25.755924,-39.302349,2.704911,-1.083267e+09,39.958427,-2.564127
10,-0.311617,0.012549,40.504332,-6.346440,-1.669300,43.661174,41.499418,39.337662,41.499418,40.733080,40.915092,-23.129839,-27.999668,2.693601,-1.249941e+09,39.516926,-1.104902
11,-0.361498,-0.062260,42.777674,-4.867459,-0.625515,43.694934,41.413728,39.132522,41.413728,40.682793,40.866666,-31.638999,-26.841587,2.745528,-1.096347e+09,39.825500,0.780867
12,-0.417288,-0.133266,41.338288,-5.999377,-0.981174,43.709492,41.300622,38.891751,41.300622,40.626527,40.808787,-33.350037,-29.372959,2.721526,-1.246694e+09,39.564392,-0.655631
13,-0.423863,-0.191385,44.466477,-4.030476,0.263950,43.655487,41.200571,38.745655,41.200571,40.582161,40.771521,-30.537869,-31.842302,2.714496,-1.125582e+09,39.970287,1.025910
14,-0.363214,-0.225751,49.885752,-0.435874,1.262306,43.579271,41.140516,38.701761,41.140516,40.559984,40.769880,-23.649520,-29.179142,2.737190,-9.871604e+08,40.734600,1.912202
15,-0.289023,-0.238405,51.759513,0.859683,1.436043,43.546090,41.114050,38.682009,41.114050,40.543268,40.780867,-13.681557,-22.622982,2.743312,-8.794276e+08,41.017090,0.693489
16,-0.311295,-0.252983,45.026025,-3.853603,0.304142,43.457728,41.012457,38.567186,41.012457,40.518902,40.744736,-15.941699,-17.757592,2.697569,-1.019449e+09,39.967930,-2.557861
17,-0.293576,-0.261102,47.789677,-2.010591,2.421562,43.223493,40.894604,38.565716,40.894604,40.517169,40.727829,-20.848906,-16.824054,2.740926,-9.033780e+08,40.364330,0.991796
18,-0.215757,-0.252033,52.696845,1.419546,4.129093,42.889426,40.794079,38.698732,40.794079,40.528735,40.745432,-19.855227,-18.881944,2.769122,-7.897436e+08,41.123894,1.881769
19,-0.167665,-0.235159,51.380432,0.543874,2.390766,42.607666,40.704710,38.801754,40.704710,40.553241,40.753708,-10.385250,-17.029794,2.739621,-8.794700e+08,40.931629,-0.467525
20,-0.095885,-0.207304,53.979018,2.354567,3.619358,42.427110,40.653676,38.880242,40.653676,40.590499,40.779550,0.476814,-9.921221,2.745246,-7.879128e+08,41.335171,0.985892
21,-0.027383,-0.171320,54.880220,2.981751,4.797199,42.237333,40.607152,38.976972,40.607152,40.628382,40.810468,4.591710,-1.772242,2.736645,-6.874156e+08,41.475204,0.338776
22,0.047238,-0.127608,56.572353,4.145760,4.607296,42.118853,40.581042,39.043232,40.581042,40.669785,40.851511,13.925124,6.331216,2.724905,-6.011020e+08,41.733936,0.623823
23,0.150988,-0.071889,60.146011,6.689122,3.686317,42.272668,40.615936,38.959203,40.615936,40.757097,40.916261,22.180854,13.565896,2.744631,-4.946804e+08,42.308369,1.376416
24,0.222978,-0.012916,59.277713,6.212469,3.204460,42.395831,40.646793,38.897755,40.646793,40.861469,40.973912,28.084462,21.396813,2.719774,-5.776984e+08,42.213421,-0.224419
25,0.181405,0.025948,49.567848,0.427692,1.288906,42.421434,40.664952,38.908469,40.664952,40.910994,40.975831,20.146310,23.470542,2.642224,-7.169336e+08,41.017090,-2.834006
26,0.012705,0.023300,39.724011,-6.863837,-1.725670,42.461952,40.627803,38.793655,40.627803,40.943408,40.902973,-8.290845,13.313309,2.581202,-9.788980e+08,39.336521,-4.097240
27,-0.128701,-0.007100,39.156295,-7.330568,-1.706661,42.454276,40.631364,38.808452,40.631364,40.994300,40.828289,-34.549949,-7.564828,2.567793,-1.124960e+09,39.222591,-0.289628
28,-0.281574,-0.061995,36.466793,-9.553047,-2.114937,42.515717,40.514698,38.513679,40.514698,41.025300,40.732661,-45.877188,-29.572661,2.552944,-1.259728e+09,38.676647,-1.391913
29,-0.384694,-0.126535,37.885063,-8.729401,-1.761276,42.577351,40.459035,38.340719,40.459035,41.029762,40.648772,-39.397682,-39.941606,2.561902,-1.146200e+09,38.845169,0.435720
30,-0.450308,-0.191290,39.061349,-8.061903,-1.965401,42.610307,40.432213,38.254118,40.432213,41.029193,40.574626,-33.203192,-39.492687,2.563718,-1.034348e+09,38.980480,0.348335
31,-0.532560,-0.259544,36.575197,-9.947388,-3.128498,42.686410,40.367412,38.048413,40.367412,41.005219,40.483731,-32.805940,-35.135605,2.530740,-1.176971e+09,38.529484,-1.156980
32,-0.535265,-0.314688,42.656993,-6.489548,-3.254303,42.697388,40.350559,38.003729,40.350559,40.968521,40.427891,-28.595016,-31.534716,2.584652,-1.007261e+09,39.227329,1.811199
33,-0.458572,-0.343465,49.472304,-2.193906,-2.205143,42.701499,40.358986,38.016473,40.358986,40.952713,40.415044,-18.764674,-26.721877,2.619511,-7.929836e+08,40.138832,2.323642
34,-0.251811,-0.325134,59.545026,5.401880,-0.367912,42.852529,40.417854,37.983180,40.417854,40.975121,40.481574,5.866593,-13.831033,2.739451,-5.268260e+08,41.911972,4.417518
35,-0.080892,-0.276285,59.913652,5.709058,0.448620,42.984217,40.466396,37.948575,40.466396,41.002750,40.548523,25.969224,4.357047,2.719706,-3.905532e+08,41.987923,0.181215
36,0.185353,-0.183958,66.948295,12.047585,1.808735,43.506957,40.649762,37.792567,40.649762,41.056538,40.685711,45.736838,25.857551,2.816483,-1.657480e+08,43.635250,3.923336
37,0.417021,-0.063762,68.103538,13.191947,1.979652,44.022556,40.829093,37.635631,40.829093,41.102397,40.830832,51.666183,41.124081,2.849752,4.057600e+06,43.950954,0.723508
38,0.610627,0.071116,68.887185,13.958469,2.226498,44.489632,40.981009,37.472386,40.981009,41.136008,40.978893,58.084125,51.829049,2.832201,1.176688e+08,44.162205,0.480650
39,0.780158,0.212924,70.053426,15.087740,2.926731,44.982157,41.158085,37.334013,41.158085,41.178592,41.134194,59.732757,56.494355,2.821886,2.105136e+08,44.473145,0.704086
40,0.954838,0.361307,72.338018,17.358462,3.109524,45.541699,41.346791,37.151884,41.346791,41.235180,41.310865,63.227795,60.348226,2.843134,3.224708e+08,45.109306,1.430440
41,1.067129,0.502471,70.770006,16.498750,2.216362,45.997981,41.519918,37.041856,41.519918,41.303149,41.472060,64.912000,62.624184,2.811888,2.176220e+08,44.937744,-0.380325
42,1.134581,0.628893,69.774496,15.967449,1.698486,46.380501,41.674866,36.969231,41.674866,41.363277,41.621430,64.592859,64.244218,2.785665,1.345068e+08,44.832886,-0.233341
43,1.141994,0.731513,65.895512,13.901993,1.706413,46.631598,41.780719,36.929839,41.780719,41.412359,41.746052,61.526820,63.677227,2.724875,3.972600e+07,44.425426,-0.908840
44,1.167862,0.818783,67.853904,15.469618,2.484200,46.941612,41.912050,36.882489,41.912050,41.470446,41.883563,61.088810,62.402830,2.722354,1.164584e+08,44.840046,0.933293
45,1.152201,0.885467,65.100591,14.016837,2.150803,47.228050,42.089020,36.949990,42.089020,41.530647,42.002359,59.272344,60.629324,2.698433,4.728240e+07,44.556484,-0.632385
46,1.113874,0.931148,63.514656,13.184214,2.138321,47.411587,42.341916,37.272246,42.341916,41.578541,42.108675,56.482996,58.948050,2.676831,-2.590840e+07,44.394455,-0.363649
47,1.096243,0.964167,65.282702,14.425496,3.098476,47.573566,42.616236,37.658906,42.616236,41.618293,42.224244,45.620338,53.791893,2.694418,4.769480e+07,44.708981,0.708479
48,1.061003,0.983534,64.091834,13.832539,3.000725,47.592555,42.912253,38.231952,42.912253,41.647545,42.329699,34.736758,45.613364,2.681318,-1.326800e+07,44.596996,-0.250474
49,1.044112,0.995650,65.806965,14.983597,4.229015,47.574091,43.214141,38.854192,43.214141,41.690823,42.443176,22.112272,34.156456,2.670367,6.696560e+07,44.882931,0.641152
50,1.014988,0.999517,65.219797,14.709168,4.753399,47.457197,43.506762,39.556327,43.506762,41.740364,42.549386,-9.602693,15.748779,2.645846,-2.597040e+07,44.832886,-0.111501

In [17]:
y = indicators_with_price["Return"]
y_2 = indicators_with_price["SMA_SHORT"]
y_3 = indicators_with_price["EMA"]
y_4 = indicators_with_price["Upper_BB"]
y_5 = indicators_with_price["Middle_BB"]
y_6 = indicators_with_price["Lower_BB"]
X = np.array(date)

trace = go.Scatter(x=X, y=y, mode="lines", name="Adj Close")
trace_2 = go.Scatter(x=X, y=y_2, mode="lines", name="SMA")
trace_3 = go.Scatter(x=X, y=y_3, mode="lines", name="EMA")
trace_4 = go.Scatter(x=X, y=y_4, mode="lines", name="Upper_BB")
trace_5 = go.Scatter(x=X, y=y_5, mode="lines", name="Middle_BB")
trace_6 = go.Scatter(x=X, y=y_6, mode="lines", name="Lower_BB")



layout = go.Layout(
    title='Stock Price and Volume',
    xaxis=dict(title='Date'),
    yaxis=dict(title='Adj Close', side='left', rangemode='tozero'),
    yaxis2=dict(title='SMA', side='right', overlaying='y', rangemode='tozero'),
    yaxis3=dict(title='EMA', side='right', overlaying='y', rangemode='tozero'),
    yaxis4=dict(title='Upper_BB', side='right', overlaying='y', rangemode='tozero'),
    yaxis5=dict(title='Middle_BB', side='right', overlaying='y', rangemode='tozero'),
    yaxis6=dict(title='Lower_BB', side='right', overlaying='y', rangemode='tozero'),
    height=600,
)

fig = go.Figure(data=[trace, trace_2, trace_3, trace_4, trace_5, trace_6], layout=layout)

# Show plot
pyo.iplot(fig)

In [18]:
class RollingWindowDataset(Dataset):
    def __init__(self, X, y, window_size, device="gpu"):
        self.X = X.clone().detach().to(torch.float).to(device)
        self.y = y.clone().detach().to(torch.float).to(device)
        self.window_size = window_size

    def __len__(self):
        # Adjust the length to account for window size
        return len(self.X) - self.window_size 

    def __getitem__(self, idx):
        # Ensure idx is within the valid range
        if idx + self.window_size > len(self.X):
            raise IndexError("Index out of bounds")

        X_window = self.X[idx : idx + self.window_size]
        
        y_target = self.y[idx + self.window_size]  

        return X_window.clone().detach().to(torch.float), y_target.clone().detach().to(torch.float)

In [19]:
X = indicators_with_price.iloc[:,:-1]
y = indicators_with_price.iloc[:,-2]

signal_true = indicators_with_price.iloc[:,-1]
y

1        42.405682
2        42.256134
3        41.610504
4        41.596272
5        40.653915
           ...
1470    182.679993
1471    188.630005
1472    191.559998
1473    193.889999
1474    195.179993
Name: Adj Close, Length: 1474, dtype: float64

In [20]:
train_signal_true = signal_true.iloc[:int(len(X)*0.8)]
test_signal_true = signal_true.iloc[int(len(X)*0.8):]
test_signal_true

1180    1.297136
1181    0.378186
1182   -2.168019
1183    1.466110
1184    0.592634
          ...
1470   -0.517351
1471    3.257068
1472    1.553301
1473    1.216330
1474    0.665322
Name: Return, Length: 295, dtype: float64

In [21]:
correlation_matrix = X.corr()

# Perform hierarchical clustering to find the order of features
linked = sch.linkage(sch.distance.pdist(correlation_matrix), method='ward')
cluster_order = sch.dendrogram(linked, no_plot=True)['leaves']

# Reorder the correlation matrix
correlation_matrix_ordered = correlation_matrix.iloc[cluster_order, cluster_order]

# Create the heatmap with text
fig = go.Figure(data=go.Heatmap(
                    z=correlation_matrix_ordered,
                    x=correlation_matrix_ordered.columns,
                    y=correlation_matrix_ordered.columns,
                    colorscale='Viridis',
                    text=correlation_matrix_ordered.round(2).values, 
                    texttemplate="%{text}",
                    textfont={"size":9}  
                    ))

fig.update_layout(
    title='Ordered Correlation Matrix',
    xaxis_title="Variables",
    yaxis_title="Variables",
    xaxis=dict(side='bottom'),
    yaxis=dict(autorange='reversed'),
    width=1000,  
    height=1000,  
)

pyo.iplot(fig)

In [22]:
X= X.iloc[:, cluster_order]

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

y_test.head(44)

1180    149.882233
1181    150.449066
1182    147.187302
1183    149.345230
1184    150.230301
1185    147.286743
1186    143.418365
1187    140.385315
1188    147.207184
1189    147.485626
1190    146.988419
1191    145.814972
1192    142.115646
1193    140.156601
1194    141.857086
1195    141.369812
1196    143.686859
1197    144.661423
1198    142.413986
1199    135.741272
1200    133.762344
1201    131.634216
1202    131.564636
1203    134.697113
1204    131.495010
1205    131.127060
1206    129.307236
1207    125.339409
1208    128.889572
1209    129.207779
1210    124.374802
1211    125.657639
1212    124.325089
1213    128.899506
1214    129.426544
1215    130.003326
1216    132.748016
1217    132.668442
1218    134.010941
1219    135.184372
1220    134.458450
1221    134.518112
1222    137.103653
1223    140.325638
Name: Adj Close, dtype: float64

In [24]:
X_train_df = pd.DataFrame()
X_test_df = pd.DataFrame()
scaler_dict = {}

X_train_df = X_train
X_test_df = X_test

for column in X_train.columns:

    if column not in ["Adj Close", "Return"]:
        scaler = MinMaxScaler()

        X_train_scaled = scaler.fit_transform(X_train[[column]].values)
        X_train_df[column] = X_train_scaled
            
        X_test_scaled = scaler.transform(X_test[[column]].values)
        X_test_df[column] = X_test_scaled

        scaler_dict[column] = scaler


X_train_df.head(24)

features = X_train_df.columns
X_train_df

,ATR,OBV,Adj Close,Lower_BB,Upper_BB,Middle_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,MACD,MACD_signal,MOM,RSI,CMO
1,0.177936,0.261686,42.405682,0.048691,0.032213,0.037797,0.037797,0.016755,0.014072,0.483867,0.507175,0.508804,0.493383,0.498961,0.567550,0.468235
2,0.172548,0.234481,42.256134,0.049438,0.032346,0.038231,0.038231,0.016988,0.014472,0.447235,0.458579,0.506461,0.494198,0.494287,0.542886,0.458078
3,0.163379,0.211390,41.610504,0.050206,0.032106,0.038478,0.038478,0.017095,0.014632,0.405927,0.409500,0.500513,0.493523,0.481206,0.443455,0.414998
4,0.162440,0.197825,41.596272,0.051265,0.031682,0.038770,0.038770,0.017129,0.014780,0.361068,0.365721,0.495417,0.491846,0.483625,0.441358,0.414059
5,0.155021,0.172243,40.653915,0.051365,0.031623,0.038787,0.038787,0.017044,0.014595,0.300403,0.313373,0.485741,0.488346,0.463760,0.315469,0.353465
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1175,0.850804,0.753803,146.053635,0.738088,0.800862,0.778358,0.778358,0.818604,0.829435,0.680159,0.631199,0.340107,0.343542,0.360230,0.463732,0.349552
1176,0.849088,0.770024,148.867905,0.744000,0.803314,0.782527,0.782527,0.817400,0.830427,0.747328,0.665570,0.388138,0.347930,0.321213,0.506323,0.377026
1177,0.803296,0.757360,147.455795,0.746416,0.805266,0.784731,0.784731,0.816305,0.830887,0.835637,0.739664,0.418622,0.358240,0.420018,0.480798,0.363377
1178,0.812802,0.772871,149.206009,0.747900,0.808367,0.787087,0.787087,0.815668,0.831932,0.856512,0.802536,0.453092,0.374178,0.423562,0.508857,0.380638
1179,0.765325,0.761787,147.962952,0.749683,0.810260,0.788953,0.788953,0.814627,0.832500,0.850520,0.839325,0.473178,0.391410,0.443981,0.484406,0.368317

In [25]:
scaler_adj = MinMaxScaler()
scaler_adj.fit(X_train[["Adj Close"]].values)

X_train_df['Adj Close'] = scaler_adj.transform(X_train[['Adj Close']].values).flatten()
X_test_df['Adj Close'] = scaler_adj.transform(X_test[['Adj Close']].values).flatten()

y_train = scaler_adj.transform(y_train.values.reshape(-1,1)).flatten()
y_test = scaler_adj.transform(y_test.values.reshape(-1,1)).flatten()

X_test_df

,ATR,OBV,Adj Close,Lower_BB,Upper_BB,Middle_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,MACD,MACD_signal,MOM,RSI,CMO
1180,0.764804,0.775662,0.793797,0.751875,0.813419,0.791684,0.791684,0.814103,0.833706,0.876576,0.853920,0.499847,0.411144,0.487570,0.517395,0.387563
1181,0.724521,0.788577,0.797684,0.752021,0.816205,0.793223,0.793223,0.813227,0.835055,0.895161,0.867699,0.523637,0.432238,0.448749,0.527281,0.393264
1182,0.685711,0.778442,0.775317,0.751879,0.815520,0.792793,0.792793,0.810946,0.835217,0.907287,0.887937,0.523008,0.448973,0.379729,0.456308,0.359879
1183,0.661728,0.787383,0.790114,0.752318,0.813808,0.792104,0.792104,0.810434,0.836117,0.913914,0.901248,0.534245,0.464868,0.444493,0.497612,0.382097
1184,0.623616,0.797445,0.796183,0.752139,0.815320,0.792814,0.792814,0.809834,0.837282,0.923476,0.911343,0.547371,0.480512,0.467133,0.514480,0.391191
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1470,0.263755,0.912203,1.018693,1.078159,1.105702,1.104494,1.104494,1.140327,1.152418,0.696649,0.699736,0.331987,0.360467,0.438975,0.219194,0.330142
1471,0.316961,0.925666,1.059493,1.079371,1.099583,1.101858,1.101858,1.142176,1.152792,0.728273,0.697238,0.358007,0.354748,0.530972,0.456178,0.434229
1472,0.316624,0.937531,1.079584,1.082407,1.093074,1.099905,1.099905,1.144078,1.154161,0.814261,0.731129,0.396416,0.358741,0.534505,0.541662,0.480564
1473,0.323439,0.947909,1.095561,1.083019,1.091863,1.099564,1.099564,1.145941,1.156274,0.926300,0.813002,0.440664,0.371807,0.555951,0.601115,0.515679
1474,0.300461,0.955220,1.104406,1.082644,1.092553,1.099746,1.099746,1.147838,1.158738,0.984412,0.904318,0.483036,0.391711,0.550955,0.631899,0.534629

In [26]:
correlation_matrix = X_train_df.corr()

# Create the heatmap with text
fig = go.Figure(data=go.Heatmap(
                    z=correlation_matrix,
                    x=correlation_matrix.columns,
                    y=correlation_matrix.columns,
                    colorscale='Viridis',
                    text=correlation_matrix.round(2).values,  
                    texttemplate="%{text}",
                    textfont={"size":9}  
                    ))

# Update the layout
fig.update_layout(
    title='Correlation Matrix',
    xaxis_title="Variables",
    yaxis_title="Variables",
    xaxis=dict(side='bottom'),
    yaxis=dict(autorange='reversed'),
    width=1000, 
    height=1000,  
)

pyo.iplot(fig)

In [27]:
X_train_tensor = torch.tensor(X_train_df.to_numpy(), dtype=torch.float, device=device)
y_train_tensor = torch.tensor(y_train, dtype=torch.float, device=device)

X_test_tensor = torch.tensor(X_test_df.to_numpy(), dtype=torch.float, device=device)
y_test_tensor = torch.tensor(y_test, dtype=torch.float, device=device)

train_data = RollingWindowDataset(X_train_tensor, y_train_tensor, window_size=time_step, device=device)
test_data = RollingWindowDataset(X_test_tensor, y_test_tensor, window_size=time_step, device=device)

print(test_data.__getitem__(0)[1])
print(test_data.__getitem__(1)[0])

tensor(0.7379, device='cuda:0')
tensor([[0.7245, 0.7886, 0.7977, 0.7520, 0.8162, 0.7932, 0.7932, 0.8132, 0.8351,
         0.8952, 0.8677, 0.5236, 0.4322, 0.4487, 0.5273, 0.3933],
        [0.6857, 0.7784, 0.7753, 0.7519, 0.8155, 0.7928, 0.7928, 0.8109, 0.8352,
         0.9073, 0.8879, 0.5230, 0.4490, 0.3797, 0.4563, 0.3599],
        [0.6617, 0.7874, 0.7901, 0.7523, 0.8138, 0.7921, 0.7921, 0.8104, 0.8361,
         0.9139, 0.9012, 0.5342, 0.4649, 0.4445, 0.4976, 0.3821],
        [0.6236, 0.7974, 0.7962, 0.7521, 0.8153, 0.7928, 0.7928, 0.8098, 0.8373,
         0.9235, 0.9113, 0.5474, 0.4805, 0.4671, 0.5145, 0.3912],
        [0.5981, 0.7914, 0.7760, 0.7537, 0.8163, 0.7941, 0.7941, 0.8092, 0.8374,
         0.9237, 0.9172, 0.5399, 0.4914, 0.4592, 0.4471, 0.3605],
        [0.5869, 0.7794, 0.7495, 0.7546, 0.8078, 0.7900, 0.7900, 0.8083, 0.8361,
         0.8756, 0.9035, 0.5112, 0.4936, 0.4080, 0.3677, 0.3216],
        [0.5854, 0.7650, 0.7287, 0.7521, 0.8019, 0.7857, 0.7857, 0.8063, 0.8339,
         0.7960, 0.8581, 0.4709, 0.4865, 0.3590, 0.3118, 0.2921],
        [0.6453, 0.7842, 0.7755, 0.7524, 0.8000, 0.7849, 0.7849, 0.8050, 0.8341,
         0.7774, 0.8059, 0.4782, 0.4824, 0.4654, 0.4544, 0.3639],
        [0.6088, 0.7965, 0.7774, 0.7533, 0.8016, 0.7861, 0.7861, 0.8043, 0.8344,
         0.7888, 0.7750, 0.4855, 0.4807, 0.5578, 0.4597, 0.3667],
        [0.5723, 0.7852, 0.7740, 0.7605, 0.8012, 0.7895, 0.7895, 0.8036, 0.8345,
         0.8188, 0.7831, 0.4882, 0.4800, 0.6035, 0.4490, 0.3617],
        [0.5827, 0.7733, 0.7659, 0.7687, 0.7993, 0.7924, 0.7924, 0.8030, 0.8343,
         0.7983, 0.7906, 0.4834, 0.4783, 0.5378, 0.4231, 0.3496],
        [0.5960, 0.7621, 0.7405, 0.7742, 0.7969, 0.7939, 0.7939, 0.8019, 0.8327,
         0.7377, 0.7723, 0.4583, 0.4714, 0.4486, 0.3463, 0.3124],
        [0.5765, 0.7501, 0.7271, 0.7765, 0.7958, 0.7944, 0.7944, 0.8003, 0.8305,
         0.6628, 0.7167, 0.4275, 0.4590, 0.4211, 0.3088, 0.2931],
        [0.5583, 0.7608, 0.7388, 0.7927, 0.7862, 0.7972, 0.7972, 0.7992, 0.8291,
         0.6220, 0.6538, 0.4137, 0.4460, 0.4535, 0.3519, 0.3121],
        [0.5622, 0.7477, 0.7354, 0.7881, 0.7872, 0.7955, 0.7955, 0.7992, 0.8275,
         0.6178, 0.6111, 0.4007, 0.4327, 0.5122, 0.3416, 0.3072],
        [0.5462, 0.7599, 0.7513, 0.7864, 0.7852, 0.7936, 0.7936, 0.8002, 0.8268,
         0.6636, 0.6114, 0.4045, 0.4229, 0.5364, 0.4019, 0.3333],
        [0.5764, 0.7761, 0.7580, 0.7854, 0.7842, 0.7926, 0.7926, 0.8007, 0.8264,
         0.7016, 0.6398, 0.4138, 0.4171, 0.5657, 0.4266, 0.3443],
        [0.5921, 0.7619, 0.7426, 0.7831, 0.7816, 0.7901, 0.7901, 0.8003, 0.8253,
         0.7177, 0.6754, 0.4089, 0.4114, 0.5461, 0.3718, 0.3205],
        [0.6206, 0.7448, 0.6968, 0.7701, 0.7853, 0.7857, 0.7857, 0.7988, 0.8220,
         0.6670, 0.6766, 0.3676, 0.3977, 0.4085, 0.2382, 0.2535],
        [0.6081, 0.7171, 0.6833, 0.7563, 0.7869, 0.7798, 0.7798, 0.7972, 0.8181,
         0.6070, 0.6429, 0.3250, 0.3771, 0.4402, 0.2052, 0.2347],
        [0.5959, 0.7034, 0.6687, 0.7415, 0.7876, 0.7730, 0.7730, 0.7961, 0.8136,
         0.5756, 0.5922, 0.2812, 0.3510, 0.3655, 0.1712, 0.2147],
        [0.5762, 0.6900, 0.6682, 0.7281, 0.7892, 0.7673, 0.7673, 0.7949, 0.8093,
         0.5907, 0.5650, 0.2486, 0.3227, 0.3484, 0.1700, 0.2140],
        [0.5879, 0.7049, 0.6897, 0.7227, 0.7841, 0.7620, 0.7620, 0.7944, 0.8063,
         0.6254, 0.5716, 0.2435, 0.2990, 0.3853, 0.2674, 0.2523],
        [0.5853, 0.6914, 0.6677, 0.7149, 0.7784, 0.7552, 0.7552, 0.7935, 0.8023,
         0.6347, 0.5927, 0.2238, 0.2756, 0.3520, 0.2091, 0.2214],
        [0.5572, 0.6804, 0.6652, 0.7066, 0.7750, 0.7494, 0.7494, 0.7919, 0.7984,
         0.6337, 0.6080, 0.2090, 0.2536, 0.3005, 0.2026, 0.2178],
        [0.5297, 0.6685, 0.6527, 0.6956, 0.7754, 0.7442, 0.7442, 0.7907, 0.7940,
         0.6029, 0.6000, 0.1900, 0.2318, 0.2520, 0.1704, 0.2003],
        [0.5433, 0.6538, 0.6255, 0.6795, 0.7799, 0.7388, 0.7388, 0.7882, 0.7885,
         0.5879, 0.5833, 0.1556, 0.2067, 0.1687, 0.1075, 0.1632],
        [0.5557, 0.6668, 0.6498, 0.6728, 0.7734, 0.7321, 0.7321, 0.7862, 0.7844,
         0.5958, 0.5698, 0.1525, 0.1859, 0.2481, 0.2212, 0.2082],
        [0.5256, 0.6801, 0.6520, 0.6687, 0.7647, 0.7255, 0.7255, 0.7841, 0.7806,
         0.6128, 0.5733, 0.1555, 0.1699, 0.3070, 0.2309, 0.2122],
        [0.5644, 0.6608, 0.6189, 0.6593, 0.7577, 0.7173, 0.7173, 0.7814, 0.7753,
         0.6174, 0.5839, 0.1339, 0.1523, 0.1158, 0.1491, 0.1668],
        [0.5617, 0.6761, 0.6277, 0.6536, 0.7491, 0.7100, 0.7100, 0.7783, 0.7707,
         0.6084, 0.5883, 0.1280, 0.1369, 0.1605, 0.1898, 0.1832],
        [0.5389, 0.6622, 0.6185, 0.6454, 0.7445, 0.7035, 0.7035, 0.7746, 0.7658,
         0.5885, 0.5796, 0.1197, 0.1227, 0.1768, 0.1673, 0.1708],
        [0.5646, 0.6773, 0.6499, 0.6428, 0.7391, 0.6994, 0.6994, 0.7712, 0.7627,
         0.6410, 0.5880, 0.1434, 0.1167, 0.3005, 0.3052, 0.2288],
        [0.5655, 0.6895, 0.6535, 0.6425, 0.7308, 0.6949, 0.6949, 0.7684, 0.7599,
         0.6945, 0.6188, 0.1686, 0.1175, 0.3813, 0.3198, 0.2353],
        [0.5445, 0.7006, 0.6575, 0.6433, 0.7222, 0.6908, 0.6908, 0.7663, 0.7575,
         0.7638, 0.6813, 0.1951, 0.1240, 0.3916, 0.3365, 0.2425],
        [0.5309, 0.7126, 0.6763, 0.6492, 0.7093, 0.6868, 0.6868, 0.7630, 0.7561,
         0.8140, 0.7430, 0.2347, 0.1381, 0.4185, 0.4132, 0.2767],
        [0.5074, 0.7002, 0.6758, 0.6595, 0.6915, 0.6825, 0.6825, 0.7600, 0.7548,
         0.8756, 0.8075, 0.2680, 0.1568, 0.4105, 0.4111, 0.2759],
        [0.4925, 0.7102, 0.6850, 0.6695, 0.6765, 0.6794, 0.6794, 0.7577, 0.7540,
         0.9451, 0.8721, 0.3040, 0.1797, 0.4830, 0.4490, 0.2927],
        [0.4790, 0.7212, 0.6930, 0.6699, 0.6757, 0.6792, 0.6792, 0.7563, 0.7536,
         0.9697, 0.9276, 0.3408, 0.2063, 0.3519, 0.4816, 0.3075],
        [0.4712, 0.7092, 0.6880, 0.6696, 0.6765, 0.6795, 0.6795, 0.7558, 0.7530,
         0.9536, 0.9554, 0.3670, 0.2334, 0.3087, 0.4586, 0.2993],
        [0.4465, 0.7192, 0.6884, 0.6689, 0.6791, 0.6805, 0.6805, 0.7554, 0.7524,
         0.9231, 0.9476, 0.3890, 0.2600, 0.3267, 0.4604, 0.3001],
        [0.4445, 0.7331, 0.7062, 0.6665, 0.6851, 0.6825, 0.6825, 0.7552, 0.7528,
         0.9317, 0.9341, 0.4219, 0.2886, 0.3368, 0.5376, 0.3335],
        [0.4810, 0.7472, 0.7283, 0.6614, 0.6937, 0.6846, 0.6846, 0.7554, 0.7542,
         0.9518, 0.9335, 0.4667, 0.3215, 0.3912, 0.6197, 0.3738],
        [0.4616, 0.7587, 0.7379, 0.6561, 0.7057, 0.6883, 0.6883, 0.7566, 0.7561,
         0.9821, 0.9545, 0.5099, 0.3575, 0.3851, 0.6520, 0.3910]],
       device='cuda:0')

# Bidirectional LSTM

<img src="/home/arda/Turkcell/RNN/LSTM/Screenshot from 2024-01-30 10-33-13.png" alt="Alt text">

- Each LSTM layer computes its own hidden states independently. The outputs (hidden states) of the forward and backward LSTMs are then combined at each time step, often by concatenation or summing.

In [28]:
class StackedBiLSTMModel(nn.Module):
    def __init__(self, input_dim, hidden_size, layer_size, output_dim, dropout_prob):
        super(StackedBiLSTMModel, self).__init__()

        self.hidden_size = hidden_size
        self.layer_size = layer_size

        # Bidirectional LSTM Layer
        self.lstm = nn.LSTM(input_size=input_dim, hidden_size=hidden_size, num_layers=layer_size, bidirectional=True, dropout=(dropout_prob if layer_size > 1 else 0), batch_first=True)
        
        # Dropout layer
        self.dropout = nn.Dropout(dropout_prob)

        # Fully connected layer
        self.fc = nn.Linear(hidden_size * 2, output_dim)  # Multiply by 2 for bidirectional

    def forward(self, x):
        # Initialize hidden and cell states
        h0 = torch.zeros(self.layer_size * 2, x.size(0), self.hidden_size).to(x.device)  # Multiply by 2 for bidirectional
        c0 = torch.zeros(self.layer_size * 2, x.size(0), self.hidden_size).to(x.device)

        # Forward propagate LSTM
        out, _ = self.lstm(x, (h0, c0))  # Output shape: (batch, seq_len, hidden_size * 2)

        # Apply dropout
        out = self.dropout(out[:, -1, :])  # Get the last time step output

        # Fully connected layer
        out = self.fc(out)

        return out

In [29]:
class ModelActioner:
    
    def __init__(self, train_data, test_data, device):
        self.train_data = train_data
        self.test_data = test_data
        self.device = device
        self.model = None
        self.optimizer = None
        self.criterion = nn.MSELoss()

    
    def train_validate(self, config, trial):

        batch_size = config["batch_size"]
        epochs = config["epochs"]
        hidden_size = config["hidden_size"]
        num_layers = config["num_layers"]
        learning_rate = config["learning_rate"]
        dropout_prob = config["dropout_prob"]
        weight_decay = config["weight_decay"]
        lr_step_size = config["lr_step_size"]
        gamma = config["gamma"]
        
        self.model = StackedBiLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, output_dim=1).to(self.device)

        n_splits = 5
        tscv = TimeSeriesSplit(n_splits=n_splits)

        val_losses = []

        for fold, (train_ids, val_ids) in enumerate(tscv.split(self.train_data)):
            print(f'Starting fold {fold+1}:')

            self.optimizer = optim.Adam(self.model.parameters(), lr = learning_rate, weight_decay=weight_decay)

            scheduler = ReduceLROnPlateau(self.optimizer, patience=lr_step_size, factor=gamma, mode="min", verbose=True) 

            train_subset = Subset(self.train_data, train_ids)
            val_subset = Subset(self.train_data, val_ids)
            
            # Creating data loader
            train_loader = DataLoader(dataset=train_subset, batch_size=batch_size, shuffle=False)
            val_loader = DataLoader(dataset=val_subset, batch_size=batch_size, shuffle=False)

            # Training Loop
            for epoch in range(epochs):
                print('epochs {}/{}'.format(epoch+1,epochs))

                running_loss = 0.0
                total_sample_train = 0

                self.model.train()

                for batch_idx, (data, target) in enumerate(train_loader):
                    data, target = data.to(self.device), target.to(self.device)
                    target = target.view(-1,1)


                    self.optimizer.zero_grad()
                    preds = self.model(data)

                    loss = self.criterion(preds, target)
                    loss.backward()
                    self.optimizer.step() # Update model params

                    running_loss += loss.item() * data.size(0)
                    total_sample_train += data.size(0)

                train_loss = running_loss/total_sample_train
                #print(f"train loss: {train_loss}")

                self.model.eval()
                val_running_loss = 0.0
                total_sample_val = 0

                with torch.no_grad():

                    for batch_idx, (data, target) in enumerate(val_loader):
                        data, target = data.to(self.device), target.to(self.device)
                        target = target.view(-1,1)

                        preds = self.model(data)
                        loss = self.criterion(preds, target)

                        val_running_loss += loss.item() * data.size(0)
                        total_sample_val += data.size(0)
                
                if trial.should_prune():
                    raise optuna.TrialPruned()
                
                val_loss = val_running_loss/total_sample_val
                val_losses.append(val_loss)
                scheduler.step(val_loss)
                
                unique_step = fold * epochs + epoch
                trial.report(val_loss, unique_step)

                current_lr = self.optimizer.param_groups[0]['lr']

                print(f'Current Learning Rate: {current_lr}')
                print(f"train_loss: {train_loss}, val_loss: {val_loss}")
                
        mean_val_loss = np.mean(val_losses)
        print(f"Mean validation loss: {mean_val_loss}")
        return mean_val_loss
    
                    
    def train(self, config):
        
        batch_size = config["batch_size"]
        epochs = config["epochs"]
        hidden_size = config["hidden_size"]
        num_layers = config["num_layers"]
        learning_rate = config["learning_rate"]
        dropout_prob = config["dropout_prob"]
        weight_decay = config["weight_decay"]
        lr_step_size = config["lr_step_size"]
        gamma = config["gamma"]
        
        self.model = StackedBiLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, output_dim=1).to(self.device)

        # Update optimizer with updated lr
        self.optimizer = optim.Adam(self.model.parameters(), lr = learning_rate, weight_decay=weight_decay)

        # Creating data loader
        train_loader = DataLoader(dataset=self.train_data, batch_size=batch_size, shuffle=False)

        scheduler = ReduceLROnPlateau(self.optimizer, patience=lr_step_size, factor=gamma, mode="min", verbose=True)  

        # Training Loop
        for epoch in range(epochs):
            print('epochs {}/{}'.format(epoch+1,epochs))

            running_loss = 0.0
            total_sample_train = 0

            self.model.train()

            for batch_idx, (data, target) in enumerate(train_loader):

                data, target = data.to(self.device), target.to(self.device)
                target = target.view(-1,1)  

                self.optimizer.zero_grad()
                preds = self.model(data)

                loss = self.criterion(preds, target)
                loss.backward()
                self.optimizer.step() # Update model params

                running_loss += loss.item() * data.size(0)
                total_sample_train += data.size(0)

            train_loss = running_loss/total_sample_train
            #print(f"train loss: {train_loss}")
            scheduler.step(train_loss)
            current_lr = self.optimizer.param_groups[0]['lr']

            print(f'Current Learning Rate: {current_lr}')
            print(f"train_loss: {train_loss}")
        
        return self.model
            
    
    def test(self, config):
        batch_size = config["batch_size"]
        all_preds = []

        test_loader = DataLoader(dataset=self.test_data, batch_size=batch_size, shuffle=False)

        running_loss = .0
        total_sample = 0

        self.model.eval()

        with torch.no_grad():

            for batch_idx, (data, target) in enumerate(test_loader):

                data, target = data.to(self.device), target.to(self.device)
                target = target.view(-1,1)
                
                preds = self.model(data)
                loss = self.criterion(preds, target)

                running_loss += loss.item() * data.size(0)
                total_sample += data.size(0)

                all_preds.extend(preds.cpu().numpy())

            test_loss = running_loss/total_sample
            print(f"test_loss: {test_loss}")

        return all_preds

In [30]:
def objective(trial):
    
    config = {
        "batch_size": trial.suggest_int("batch_size", 32, 128, log=True),
        "epochs": trial.suggest_int("epochs", 50, 150),
        "hidden_size": trial.suggest_int("hidden_size", 10, 100),
        "learning_rate": trial.suggest_float("learning_rate", 1e-6, 1e-1, log=True),
        "dropout_prob": trial.suggest_float("dropout_prob", 0.0, 0.2),
        "weight_decay": trial.suggest_float("weight_decay", 1e-6, 1e-2, log=True),
        "lr_step_size": trial.suggest_int("lr_step_size", 5, 100), 
        "gamma": trial.suggest_float("gamma", 0.1, 0.9),
        "num_layers": trial.suggest_int("num_layers", 1, 5)
    }

    trainer = ModelActioner(train_data, test_data, device)

    val_loss = trainer.train_validate(config, trial)

    return val_loss

In [31]:
study_name = "Vanilla-LSTM-Tunner"
storage_url = "sqlite:///db.sqlite3"

optuna.delete_study(study_name=study_name, storage= storage_url)

study = optuna.create_study(direction='minimize', 
                            storage=storage_url, 
                            sampler=TPESampler(),
                            pruner=optuna.pruners.HyperbandPruner(
                            min_resource=30,  
                            max_resource=150,  
                            reduction_factor=3,  
                            ),
                            study_name=study_name,
                            load_if_exists=False)

pbar = tqdm(total=10, desc='Optimizing', unit='trial')

def callback(study, trial):
    # Update the progress bar
    pbar.update(1)
    # Optionally, you can include additional information in the progress bar
    pbar.set_postfix_str(f"Best Value: {study.best_value:.4f}")


study.optimize(objective, n_trials=10, callbacks=[callback])
pbar.close()

# Best hyperparameters
print('Number of finished trials:', len(study.trials))
print('Best trial:')
trial = study.best_trial

print('Value:', trial.value)
print('Params:')
for key, value in trial.params.items():
    print(f'{key}: {value}')

[I 2024-01-30 15:58:54,229] A new study created in RDB with name: Vanilla-LSTM-Tunner

Optimizing:   0%|          | 0/10 [00:00<?, ?trial/s]

Starting fold 1:
epochs 1/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.004403111558272749, val_loss: 0.0031992950327029185
epochs 2/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0035226224897135245, val_loss: 0.004768897873526882
epochs 3/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.002621617282458924, val_loss: 0.0014697115192089413
epochs 4/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.001742124186497868, val_loss: 0.0014912658493452158
epochs 5/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0013379736800408482, val_loss: 0.002465021328938381
epochs 6/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0015118032409717622, val_loss: 0.0021580879179367834
epochs 7/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0010572705747970185, val_loss: 0.000845863542477317
epochs 8/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0004313431865547931, val_loss: 0.001166430785257256
epochs 9/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0003078456498578338, val_loss: 0.0006847132007202143
epochs 10/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00029130834453481886, val_loss: 0.0014793600231992998
epochs 11/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00032750908331332827, val_loss: 0.0005266456899036674
epochs 12/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00032661512898477283, val_loss: 0.0017101236565313278
epochs 13/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0002988887323130927, val_loss: 0.0004683849642379086
epochs 14/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0005022336226446848, val_loss: 0.003472762842657705
epochs 15/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0009898853903378996, val_loss: 0.0006457298984478546
epochs 16/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0006014864976015432, val_loss: 0.000727058741080491
epochs 17/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0003578915872678504, val_loss: 0.0016854510133040123
epochs 18/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00035547937487105007, val_loss: 0.00046488701246701005
epochs 19/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00031578346955173303, val_loss: 0.0010847332232130356
epochs 20/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0002977156325390464, val_loss: 0.0008998758713994268
epochs 21/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00020589641315286588, val_loss: 0.0005989389106549357
epochs 22/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00020084589961793666, val_loss: 0.0008810162745397994
epochs 23/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00020472842558152287, val_loss: 0.0005571911099039464
epochs 24/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0001934421035816501, val_loss: 0.0009426338298316483
epochs 25/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00018129149029846303, val_loss: 0.0006718795441706091
epochs 26/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.000153786910193862, val_loss: 0.0006598882433853947
epochs 27/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0001532647985425827, val_loss: 0.0007292122526830998
epochs 28/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00014194991879201935, val_loss: 0.0005788444770452636
epochs 29/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00017645287826828854, val_loss: 0.0007791032059502815
epochs 30/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00013981145170155766, val_loss: 0.0006364142419255269
epochs 31/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00013229667249680988, val_loss: 0.0006928884396031554
epochs 32/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00012547222290059404, val_loss: 0.0006979693911171848
epochs 33/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00012712025303411985, val_loss: 0.000658242975900759
epochs 34/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00010911578405954826, val_loss: 0.000650997185734995
epochs 35/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0001147735019147053, val_loss: 0.0006189569853511535
epochs 36/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00012775264365604686, val_loss: 0.0007382735293600326
epochs 37/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0001248760444516512, val_loss: 0.0006676324522968138
epochs 38/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00011956845096153158, val_loss: 0.0005757133858520155
epochs 39/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00012476099731621187, val_loss: 0.0007773149343693774
epochs 40/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00010484821933986448, val_loss: 0.0006076826097312964
epochs 41/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00011081214083548586, val_loss: 0.0007166120656947704
epochs 42/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00011972994382775046, val_loss: 0.0005677946786693095
epochs 43/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00012836152918201774, val_loss: 0.0006482578737728381
epochs 44/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0001228821098936207, val_loss: 0.0007015179871718083
epochs 45/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00010994147960445844, val_loss: 0.0005734705643335089
epochs 46/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00012173397733836042, val_loss: 0.0007485727655490991
epochs 47/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00011196536177426185, val_loss: 0.0005376281315639735
epochs 48/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00011980138565137933, val_loss: 0.0007768631390458072
epochs 49/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00011986837217639396, val_loss: 0.00046143543870861534
epochs 50/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00013690229737365275, val_loss: 0.0007487392976284754
epochs 51/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00011803421423935919, val_loss: 0.0007872512307691434
epochs 52/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0001458821111507285, val_loss: 0.00038981594258633554
epochs 53/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0001890021760788697, val_loss: 0.0016345936537377793
epochs 54/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00042773331791211506, val_loss: 0.0004798689354622241
epochs 55/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0002651949797597665, val_loss: 0.0014419585013504647
epochs 56/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0002141449564078357, val_loss: 0.0003551912437259003
epochs 57/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0002889085196856238, val_loss: 0.0022899097251452053
epochs 58/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0006890912921670334, val_loss: 0.0006174255565465453
epochs 59/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00032725679499746646, val_loss: 0.0006489496271276265
epochs 60/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0002586796202721368, val_loss: 0.0007191500885205136
epochs 61/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.000145060700321521, val_loss: 0.000741407755798064
epochs 62/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00017040547467523108, val_loss: 0.000667025169913017
epochs 63/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00012058630852966177, val_loss: 0.0006073063722440219
epochs 64/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00013798848989321605, val_loss: 0.0007463681300462682
epochs 65/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00012511682055590332, val_loss: 0.0006097698205849156
epochs 66/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00012346117984730212, val_loss: 0.0005827820963118004
epochs 67/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00010396077325965866, val_loss: 0.000668539413329209
epochs 68/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00011483500707790403, val_loss: 0.000662107515035175
epochs 69/112
Current Learning Rate: 0.004894713038278157
train_loss: 8.516960829422858e-05, val_loss: 0.0006647920449554307
epochs 70/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00010892365295914811, val_loss: 0.0005612030778022941
epochs 71/112
Current Learning Rate: 0.004894713038278157
train_loss: 9.72981905904721e-05, val_loss: 0.0006204909424740383
epochs 72/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00010714368308024286, val_loss: 0.0005810638094242667
epochs 73/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00010518163827854503, val_loss: 0.0006548131828754709
epochs 74/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00010399555212643463, val_loss: 0.0004976907863074399
epochs 75/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00010914894205358762, val_loss: 0.0008037763885416401
epochs 76/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00011199846406893094, val_loss: 0.00046279182586456754
epochs 77/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0001253441002949043, val_loss: 0.000991651719790531
epochs 78/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00013965580022302579, val_loss: 0.00030783840103867027
epochs 79/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00018291936170211748, val_loss: 0.00186568823357842
epochs 80/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00047279440607924604, val_loss: 0.00045367305761184073
epochs 81/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00022880847559702633, val_loss: 0.0011179365710294977
epochs 82/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0002384199772917016, val_loss: 0.00033802485499080155
epochs 83/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00023959232379351498, val_loss: 0.0014123813651157815
epochs 84/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0004327491280970495, val_loss: 0.000773951244978148
epochs 85/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0001616593044003055, val_loss: 0.0004632373862217979
epochs 86/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0002709981533514924, val_loss: 0.0007779567784853969
epochs 87/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0001692831972736473, val_loss: 0.0006036790887481489
epochs 88/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0001717165379025238, val_loss: 0.0008337274315703393
epochs 89/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00011593087171939642, val_loss: 0.00045623447424856877
epochs 90/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00014898809811137126, val_loss: 0.0011859577410625265
epochs 91/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0002472110790365964, val_loss: 0.00042702350145662894
epochs 92/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00017822024302930866, val_loss: 0.0008415511635705895
epochs 93/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00015669526975742835, val_loss: 0.000508000180936371
epochs 94/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00012325043096911702, val_loss: 0.000634823082609776
epochs 95/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00011135543027194217, val_loss: 0.0006250406496922661
epochs 96/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00010246164230537895, val_loss: 0.0005523028987380996
epochs 97/112
Current Learning Rate: 0.004894713038278157
train_loss: 8.25063910030478e-05, val_loss: 0.0006380888060727447
epochs 98/112
Current Learning Rate: 0.004894713038278157
train_loss: 9.334112726623732e-05, val_loss: 0.0005893400081187898
epochs 99/112
Current Learning Rate: 0.004894713038278157
train_loss: 9.46368300662327e-05, val_loss: 0.0006369207183034012
epochs 100/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00010644144383963737, val_loss: 0.0004718879884003111
epochs 101/112
Current Learning Rate: 0.004894713038278157
train_loss: 9.3127117188966e-05, val_loss: 0.000737954195953472
epochs 102/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00010565211287987614, val_loss: 0.0004936671378985651
epochs 103/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00010241942643341118, val_loss: 0.0008213635244049199
epochs 104/112
Current Learning Rate: 0.004894713038278157
train_loss: 9.231512374658211e-05, val_loss: 0.0004915654538082274
epochs 105/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00010514279289820574, val_loss: 0.0008604675858227965
epochs 106/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00012547353743636784, val_loss: 0.0004207809944914299
epochs 107/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00011319706237899434, val_loss: 0.0010056170357284062
epochs 108/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00015226541968571072, val_loss: 0.000383286351202827
epochs 109/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0001323512358603215, val_loss: 0.0012097204997661283
epochs 110/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00020424405332673096, val_loss: 0.00036075670593485934
epochs 111/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00018394618049282337, val_loss: 0.0012073914337042157
epochs 112/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00019071090768863397, val_loss: 0.00039827389398986406
Starting fold 2:
epochs 1/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0008874486865253694, val_loss: 0.01867945695655647
epochs 2/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0010293174763796801, val_loss: 0.026912113824100407
epochs 3/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0004811660035264231, val_loss: 0.02020108014611261
epochs 4/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0004276993701671862, val_loss: 0.017054174333150502
epochs 5/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0006840896421731978, val_loss: 0.018483660497983532
epochs 6/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00027850692958363986, val_loss: 0.01217144762816292
epochs 7/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00034177588554784794, val_loss: 0.013201776186679367
epochs 8/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0005680027107871261, val_loss: 0.013627763355283864
epochs 9/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00028371341494793604, val_loss: 0.01164741564798292
epochs 10/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00017494944628115527, val_loss: 0.013634856985561628
epochs 11/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0005290416480698758, val_loss: 0.012551375820914963
epochs 12/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00032121968795182943, val_loss: 0.012866836354424734
epochs 13/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.000164377488641131, val_loss: 0.011427176799366457
epochs 14/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00017640525663474582, val_loss: 0.009173434717696476
epochs 15/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00016786595654049103, val_loss: 0.012360799373632603
epochs 16/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0001841096254841223, val_loss: 0.0113261884621039
epochs 17/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00017961986769312663, val_loss: 0.012650725590040483
epochs 18/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00011325184111125549, val_loss: 0.012505918597400918
epochs 19/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00018050734893714342, val_loss: 0.013639915552207086
epochs 20/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00023283032435643682, val_loss: 0.01231818571816095
epochs 21/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00016665866501422937, val_loss: 0.011748022429408535
epochs 22/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.000216891336867415, val_loss: 0.013525307891464167
epochs 23/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00019949457475621903, val_loss: 0.01088913497619735
epochs 24/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0006261800607906883, val_loss: 0.021093326315244354
epochs 25/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0012338951199025526, val_loss: 0.01868744053823686
epochs 26/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0005140576932743919, val_loss: 0.014717770313533643
epochs 27/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0004549192904614804, val_loss: 0.01617415598716843
epochs 28/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0002376425017339809, val_loss: 0.007362573712949626
epochs 29/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0001636957046317826, val_loss: 0.010939842287423927
epochs 30/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00014823315404650404, val_loss: 0.01005586233142783
epochs 31/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00014486536070705075, val_loss: 0.010386461537102208
epochs 32/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00012201097846709408, val_loss: 0.01042403089666059
epochs 33/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00010694112199781607, val_loss: 0.010246722468374563
epochs 34/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00012638272622489313, val_loss: 0.009128385395453454
epochs 35/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.0001210370606320141, val_loss: 0.009017087009774827
epochs 36/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00011653209261480709, val_loss: 0.008624925701441638
epochs 37/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00012012126449020064, val_loss: 0.009431753852084357
epochs 38/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00012142782181020368, val_loss: 0.011361810252767687
epochs 39/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00011064811807192155, val_loss: 0.010444888697565095
epochs 40/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00011783825856892116, val_loss: 0.011400110106151452
epochs 41/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00010662551581763446, val_loss: 0.010879909466316421
epochs 42/112
Current Learning Rate: 0.004894713038278157
train_loss: 0.00010477444076565669, val_loss: 0.010385807125001319
epochs 43/112
Current Learning Rate: 0.004894713038278157
train_loss: 9.938996925599576e-05, val_loss: 0.009828854242749955
epochs 44/112
Current Learning Rate: 0.004894713038278157
train_loss: 9.205477070852765e-05, val_loss: 0.010847192929648652
epochs 45/112
Current Learning Rate: 0.004894713038278157
train_loss: 9.394726486914081e-05, val_loss: 0.010855466919204604
epochs 46/112
Current Learning Rate: 0.004894713038278157
train_loss: 8.109754965380129e-05, val_loss: 0.010951064278497286
epochs 47/112
Current Learning Rate: 0.004894713038278157
train_loss: 8.791311981169062e-05, val_loss: 0.009510102120835442
epochs 48/112
Current Learning Rate: 0.004894713038278157

[W 2024-01-30 16:00:09,102] Trial 0 failed with parameters: {'batch_size': 41, 'epochs': 112, 'hidden_size': 25, 'learning_rate': 0.004894713038278157, 'dropout_prob': 0.16495738590793133, 'weight_decay': 8.44023416118608e-06, 'lr_step_size': 93, 'gamma': 0.65933602370862, 'num_layers': 3} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "/home/arda/anaconda3/lib/python3.11/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/tmp/ipykernel_60945/1715914211.py", line 17, in objective
    val_loss = trainer.train_validate(config, trial)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ipykernel_60945/1172417936.py", line 82, in train_validate
    preds = self.model(data)
            ^^^^^^^^^^^^^^^^
  File "/home/arda/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arda/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ipykernel_60945/618990335.py", line 29, in forward
    out = self.fc(out)
          ^^^^^^^^^^^^
  File "/home/arda/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arda/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arda/anaconda3/lib/python3.11/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
[W 2024-01-30 16:00:09,105] Trial 0 failed with value None.

KeyboardInterrupt:

In [ ]:
trainer = ModelActioner(train_data, test_data, device)
model = trainer.train(trial.params)

epochs 1/79

Current Learning Rate: 0.00022078935295972353
train_loss: 0.42712533657771373
epochs 2/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.3398248373805689
epochs 3/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.23089723345548702
epochs 4/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.07332626369531525
epochs 5/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.07636017390744276
epochs 6/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.05740143414668837
epochs 7/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.03519123312709484
epochs 8/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.022575530587871956
epochs 9/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.012931673994312465
epochs 10/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0075616575059550715
epochs 11/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.007493208540759423
epochs 12/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.006598943400520848
epochs 13/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0065511049066838455
epochs 14/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.006808368317241317
epochs 15/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.006151008422564436
epochs 16/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.006518086873093365
epochs 17/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005963322841090515
epochs 18/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005801536664694942
epochs 19/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005900396936314616
epochs 20/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005933429457920107
epochs 21/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005832487656755397
epochs 22/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.006089632586054996
epochs 23/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005597768408874058
epochs 24/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005688919146270348
epochs 25/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005610412602735445
epochs 26/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0054901960593061565
epochs 27/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005685053858700893
epochs 28/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005556699224965163
epochs 29/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0052570857706639735
epochs 30/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005119805763545343
epochs 31/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005579564736803198
epochs 32/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00522636233045338
epochs 33/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005953478804145353
epochs 34/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005921007672095023
epochs 35/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005709554559227063
epochs 36/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005447982252874958
epochs 37/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.007055010963723654
epochs 38/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005473930816502528
epochs 39/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00529940725501118
epochs 40/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005362264869431042
epochs 41/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005345638763233363
epochs 42/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.004738838226013378
epochs 43/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.004826552458599801
epochs 44/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0047200813715136914
epochs 45/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005108330166787894
epochs 46/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0046174542674803
epochs 47/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.004648141056249977
epochs 48/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005248996516533754
epochs 49/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005266730245900246
epochs 50/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0049603048180709985
epochs 51/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.004315629417060296
epochs 52/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005204918489089884
epochs 53/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.004872833285070464
epochs 54/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00490208308659658
epochs 55/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0053712015823842675
epochs 56/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005509660719988236
epochs 57/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005553080757981421
epochs 58/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0050178782495419755
epochs 59/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0052773590107337625
epochs 60/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005501614485576027
epochs 61/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0050934451154232155
epochs 62/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.004904136323936218
epochs 63/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005850167727376856
epochs 64/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005719756424459855
epochs 65/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.006609382697418004
epochs 66/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005246741663857408
epochs 67/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005227128663284925
epochs 68/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005370037526811272
epochs 69/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0042065985950062845
epochs 70/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.004135298536011399
epochs 71/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.004343874537948076
epochs 72/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.004219933823653648
epochs 73/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0038714786478634185
epochs 74/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0038384543953356763
epochs 75/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0038255339158116326
epochs 76/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.004367548434088409
epochs 77/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.003851193078846921
epochs 78/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.004403466994911104
epochs 79/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0040497595308931125

In [ ]:
preds = trainer.test(trial.params)
preds = np.array(preds)

y_true = y_test[time_step:]
y_true = scaler_adj.inverse_transform(y_true.reshape(-1, 1)).flatten()
preds = scaler_adj.inverse_transform(preds.reshape(-1, 1)).flatten()


mse = mean_squared_error(y_true, preds)
print(f'Mean Squared Error: {mse:.4f}')

rmse = mean_squared_error(y_true, preds, squared=False)
print(f'Root Mean Squared Error: {rmse:.4f}')

r2 = r2_score(y_true, preds)
print(f'R² Score: {r2:.4f}')

mape = mean_absolute_percentage_error(y_true, preds)*100
print(f'mape Score: % {mape:.4f}')

test_loss: 0.0018684213240797896
Mean Squared Error: 39.7373
Root Mean Squared Error: 6.3038
R² Score: 0.8153
mape Score: % 3.0146

In [ ]:
stock_price = stock_data["Adj Close"].iloc[test_index:]
stock_price=stock_price.reset_index()
stock_price=stock_price.drop(columns=["index"])
stock_price

      Adj Close
0    140.325653
1    141.737747
2    141.071472
3    143.159805
4    145.118851
..          ...
247  182.679993
248  188.630005
249  191.559998
250  193.889999
251  195.179993

[252 rows x 1 columns]

In [ ]:
signals = pd.DataFrame(preds, columns=['pred'])
signals["next_day"] = pd.DataFrame(y_true)
signals["today"] = stock_price
signals["Signal_Pred"] = (signals["today"] < signals["pred"]).astype(int)
signals["Signal_True"] = (signals["today"] < signals["next_day"]).astype(int)

signals.head(50)

          pred    next_day       today  Signal_Pred  Signal_True
0   140.881531  141.737747  140.325653            1            1
1   142.025452  141.071472  141.737747            1            0
2   143.215378  143.159805  141.071472            1            1
3   144.477158  145.118851  143.159805            1            1
4   145.809738  142.205154  145.118851            1            0
5   147.055481  143.487961  142.205154            1            1
6   148.211044  144.621628  143.487961            1            1
7   149.317261  149.981674  144.621628            1            1
8   150.518585  153.641220  149.981674            1            1
9   151.864792  150.886612  153.641220            0            0
10  153.201096  153.790375  150.886612            1            1
11  154.531586  151.075562  153.790375            1            0
12  155.742294  150.031387  151.075562            1            0
13  156.790314  150.399902  150.031387            1            1
14  157.679916  153.228439  150.399902            1            1
15  158.488434  152.581055  153.228439            1            0
16  159.216721  154.702438  152.581055            1            1
17  159.934814  153.089005  154.702438            1            0
18  160.596390  151.933685  153.089005            1            0
19  161.171127  147.880127  151.933685            1            0
20  161.546509  148.308395  147.880127            1            1
21  161.708405  148.796417  148.308395            1            1
22  161.668320  146.117294  148.796417            1            0
23  161.364059  147.322372  146.117294            1            1
24  160.883804  146.814438  147.322372            1            0
25  160.287659  144.722916  146.814438            1            0
26  159.578186  145.320511  144.722916            1            1
27  158.833847  150.419815  145.320511            1            1
28  158.280579  153.208511  150.419815            1            1
29  158.047470  150.987534  153.208511            1            0
30  158.065643  152.252396  150.987534            1            1
31  158.322617  149.981598  152.252396            1            0
32  158.658600  147.900040  149.981598            1            0
33  158.933517  149.862076  147.900040            1            1
34  159.146957  151.973526  149.862076            1            1
35  159.354874  152.371902  151.973526            1            1
36  159.595047  155.220352  152.371902            1            1
37  159.957275  154.373779  155.220352            1            0
38  160.401581  156.764084  154.373779            1            1
39  160.968460  158.636490  156.764084            1            1
40  161.661224  157.192352  158.636490            1            0
41  162.379410  158.287903  157.192352            1            1
42  163.095764  159.602570  158.287903            1            1
43  163.793152  157.640533  159.602570            1            0
44  164.389938  157.013077  157.640533            1            0
45  164.861588  160.120483  157.013077            1            1
46  165.313766  161.704041  160.120483            1            1
47  165.809326  164.233780  161.704041            1            1
48  166.413712  165.498672  164.233780            1            1
49  167.138184  164.960831  165.498672            1            0

In [ ]:
signals["Signal_Pred"].value_counts()

Signal_Pred
0    127
1    124
Name: count, dtype: int64

In [ ]:
signals["Date"] = date_test
signals

           pred    next_day       today  Signal_Pred  Signal_True       Date
0    140.881531  141.737747  140.325653            1            1 2023-01-23
1    142.025452  141.071472  141.737747            1            0 2023-01-24
2    143.215378  143.159805  141.071472            1            1 2023-01-25
3    144.477158  145.118851  143.159805            1            1 2023-01-26
4    145.809738  142.205154  145.118851            1            0 2023-01-27
..          ...         ...         ...          ...          ...        ...
246  180.227432  182.679993  183.630005            0            0 2024-01-16
247  179.823166  188.630005  182.679993            0            1 2024-01-17
248  179.591934  191.559998  188.630005            0            1 2024-01-18
249  179.598038  193.889999  191.559998            0            1 2024-01-19
250  179.876053  195.179993  193.889999            0            1 2024-01-22

[251 rows x 6 columns]

In [ ]:
stock_price = stock_data["Adj Close"].iloc[test_index:]
stock_price=stock_price.reset_index()
stock_price=stock_price.drop(columns=["index"])
stock_price

      Adj Close
0    140.325653
1    141.737747
2    141.071472
3    143.159805
4    145.118851
..          ...
247  182.679993
248  188.630005
249  191.559998
250  193.889999
251  195.179993

[252 rows x 1 columns]

In [ ]:
date_test["Date"] = date_test["Date"].dt.strftime('%Y-%m-%d')
date_test

           Date
0    2023-01-23
1    2023-01-24
2    2023-01-25
3    2023-01-26
4    2023-01-27
..          ...
247  2024-01-17
248  2024-01-18
249  2024-01-19
250  2024-01-22
251  2024-01-23

[252 rows x 1 columns]

In [ ]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=np.array(date_test).flatten(), y=stock_data["Adj Close"].iloc[test_index:], mode='lines', name='TSLA Stock Price'))

# Buy and sell signals
buy_signals = signals[signals['Signal_Pred'] == 1]
sell_signals = signals[signals['Signal_Pred'] == 0]

# Ensure that buy and sell prices are aligned with the signals by matching on the 'Date' column
buy_prices = stock_data[stock_data['Date'].isin(buy_signals['Date'])]["Adj Close"]
sell_prices = stock_data[stock_data['Date'].isin(sell_signals['Date'])]["Adj Close"]


# Plot buy signals
fig.add_trace(go.Scatter(
    x=buy_signals['Date'], 
    y=buy_prices, 
    mode='markers', 
    name='Buy', 
    marker=dict(color='green', size=10, symbol='triangle-up')
))


# Plot sell signals
fig.add_trace(go.Scatter(
    x=sell_signals['Date'], 
    y=sell_prices, 
    mode='markers', 
    name='Sell', 
    marker=dict(color='red', size=10, symbol='triangle-down')
))


# Update layout
fig.update_layout(
    title='Stock Price with Buy and Sell Signals',
    xaxis_title='Date',
    yaxis_title='Price',
    xaxis_rangeslider_visible=False,
    height = 700,
    width=1280
)

# Show the plot
pyo.iplot(fig)

/home/arda/anaconda3/lib/python3.11/site-packages/_plotly_utils/basevalidators.py:106: FutureWarning:

The behavior of DatetimeProperties.to_pydatetime is deprecated, in a future version this will return a Series containing python datetime objects instead of an ndarray. To retain the old behavior, call `np.array` on the result

In [ ]:
trace_pred = go.Scatter(
    x=np.array(date_test).flatten(),
    y=signals['pred'],
    mode='lines+markers',
    name='Predicted'
)

trace_true = go.Scatter(
    x=np.array(date_test).flatten(),
    y=signals['next_day'],
    mode='lines+markers',
    name='Actual Next Day'
)

# Define the layout
layout = go.Layout(
    title='Predicted vs Actual Next Day Values',
    xaxis=dict(title='Index'),
    yaxis=dict(title='Value'),
    height=700
)

# Create the figure and add traces
fig = go.Figure(data=[trace_pred, trace_true], layout=layout)

# Show the figure
fig.show()