In [33]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import yfinance as yf
import talib
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from torch.utils.data import Dataset, DataLoader, Subset
from sklearn.model_selection import train_test_split
import torch.optim as optim
import os
from sklearn.model_selection import TimeSeriesSplit

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, log_loss, mean_absolute_error, mean_squared_error, r2_score, mean_absolute_percentage_error
import matplotlib.pyplot as plt
import scipy.cluster.hierarchy as sch
import seaborn as sns

import optuna
from optuna.samplers import TPESampler
from optuna.trial import TrialState
from torch.optim.lr_scheduler import StepLR, ReduceLROnPlateau 
import shap
import plotly.graph_objs as go
import plotly.offline as pyo
from tqdm.auto import tqdm
from sklearn.utils.class_weight import compute_class_weight

In [34]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    print("gpu")
else:
    device = torch.device('cpu')
print(torch.__version__)
print('CUDA available:', torch.cuda.is_available())
print('CUDA version:', torch.version.cuda)
print('cuDNN version:', torch.backends.cudnn.version())

gpu
2.1.2+cu121
CUDA available: True
CUDA version: 12.1
cuDNN version: 8902

In [35]:
start_date = '2018-01-01'
end_date = '2024-01-24'

stock_data = yf.download("AAPL", start=start_date, end=end_date)[["Adj Close", "High", "Low", "Volume"]]

stock_data = stock_data.reset_index()

stock_data = stock_data[['Date', 'Adj Close', "High", "Low", "Volume"]]

stock_data = stock_data.sort_values(by="Date")
stock_data.head(45)

[*********************100%%**********************]  1 of 1 completed

         Date  Adj Close       High        Low     Volume
0  2018-01-02  40.722878  43.075001  42.314999  102223600
1  2018-01-03  40.715790  43.637501  42.990002  118071600
2  2018-01-04  40.904911  43.367500  43.020000   89738400
3  2018-01-05  41.370628  43.842499  43.262501   94640000
4  2018-01-08  41.216953  43.902500  43.482498   82271200
5  2018-01-09  41.212234  43.764999  43.352501   86336000
6  2018-01-10  41.202774  43.575001  43.250000   95839600
7  2018-01-11  41.436813  43.872501  43.622501   74670800
8  2018-01-12  41.864700  44.340000  43.912498  101672400
9  2018-01-16  41.651932  44.847500  44.035000  118263600
10 2018-01-17  42.339878  44.812500  43.767502  137547200
11 2018-01-18  42.377705  45.025002  44.562500  124773600
12 2018-01-19  42.188576  44.895000  44.352501  129700400
13 2018-01-22  41.843426  44.445000  44.150002  108434400
14 2018-01-23  41.852882  44.860001  44.205002  130756400
15 2018-01-24  41.186226  44.325001  43.299999  204420400
16 2018-01-25  40.451008  43.737499  42.632500  166116000
17 2018-01-26  40.545582  43.000000  42.514999  156572000
18 2018-01-29  39.706341  42.540001  41.767502  202561600
19 2018-01-30  39.472301  41.842499  41.174999  184192800
20 2018-01-31  39.581047  42.110001  41.625000  129915600
21 2018-02-01  39.663788  42.154999  41.689999  188923200
22 2018-02-02  37.942772  41.700001  40.025002  346375200
23 2018-02-05  36.994785  40.970001  39.000000  290954000
24 2018-02-06  38.540871  40.930000  38.500000  272975200
25 2018-02-07  37.715820  40.849998  39.767502  206434400
26 2018-02-08  36.678009  40.250000  38.757500  217562000
27 2018-02-09  37.126637  39.472500  37.560001  282690400
28 2018-02-12  38.622044  40.972500  39.377499  243278000
29 2018-02-13  39.008961  41.187500  40.412498  130196800
30 2018-02-14  39.728180  41.884998  40.720001  162579600
31 2018-02-15  41.062187  43.272499  42.250000  204588800
32 2018-02-16  40.929256  43.705002  42.942501  160704400
33 2018-02-20  40.791584  43.564999  42.855000  135722000
34 2018-02-21  40.606445  43.529999  42.752499  149886400
35 2018-02-22  40.945877  43.487499  42.927502  123967600
36 2018-02-23  41.657986  43.912498  43.384998  135249600
37 2018-02-26  42.481636  44.847500  44.052502  152648800
38 2018-02-27  42.343971  45.119999  44.540001  155712400
39 2018-02-28  42.279884  45.154999  44.512501  151128400
40 2018-03-01  41.539303  44.945000  43.165001  195208000
41 2018-03-02  41.826519  44.075001  43.112499  153816000
42 2018-03-05  41.971306  44.435001  43.630001  113605600
43 2018-03-06  41.935699  44.562500  44.032501   95154000
44 2018-03-07  41.546410  43.962502  43.567501  126814000

In [36]:
time_step = 44

In [37]:
test_index = int((len(stock_data)-44)*0.8+44+44)

In [38]:
date = stock_data["Date"].iloc[time_step:].dt.strftime('%Y-%m-%d')
date_test = stock_data["Date"].iloc[test_index:].reset_index()
date_test.drop(columns=["index"], inplace=True)
date_test

          Date
0   2023-01-23
1   2023-01-24
2   2023-01-25
3   2023-01-26
4   2023-01-27
..         ...
247 2024-01-17
248 2024-01-18
249 2024-01-19
250 2024-01-22
251 2024-01-23

[252 rows x 1 columns]

In [39]:
def add_technical_indicators(data, timeperiod=time_step):

    # MACD
    macd, macdsignal, macdhist = talib.MACD(data["Adj Close"], fastperiod=12, slowperiod=26, signalperiod=9)

    rsi = talib.RSI(data["Adj Close"], timeperiod=14)

    # CMO
    cmo = talib.CMO(data["Adj Close"], timeperiod=timeperiod)

    # MOM
    mom = talib.MOM(data["Adj Close"], timeperiod=timeperiod)

    # Bollinger Bands
    upperband, middleband, lowerband = talib.BBANDS(data["Adj Close"], timeperiod=20, nbdevup=2, nbdevdn=2, matype=0)

    # SMA
    sma_s = talib.SMA(data["Adj Close"], timeperiod=20)
    sma_l = talib.SMA(data["Adj Close"], timeperiod=50)

    # Calculate Exponential Moving Average (EMA)
    ema = talib.EMA(data["Adj Close"], timeperiod=timeperiod)

    # Calculate Stochastic Oscillator
    slowk, slowd = talib.STOCH(data['High'], data['Low'], data['Adj Close'], fastk_period=14, slowk_period=3, slowk_matype=0, slowd_period=3, slowd_matype=0)

    # Calculate Average True Range (ATR)
    atr = talib.ATR(data['High'], data['Low'], data['Adj Close'], timeperiod=14)

    # Calculate On-Balance Volume (OBV)
    obv = talib.OBV(data['Adj Close'], data['Volume'])

    # Combine all indicators into a DataFrame
    indicators = pd.DataFrame({
        'MACD': macd,
        'MACD_signal': macdsignal,
        'RSI': rsi,
        'CMO': cmo,
        'MOM': mom,
        'Upper_BB': upperband,
        'Middle_BB': middleband,
        'Lower_BB': lowerband,
        'SMA_SHORT': sma_s,
        'SMA_LONG': sma_l,
        'EMA': ema,
        'SLOWK': slowk,
        'SLOWD': slowd,
        'ATR': atr,
        'OBV': obv,

    })
    return indicators

In [40]:
indicators = add_technical_indicators(stock_data)
indicators.head(45)

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102223600.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-15848000.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73890400.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168530400.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86259200.0
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-76800.0
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-95916400.0
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-21245600.0
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80426800.0
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-37836800.0
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99710400.0
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,224484000.0
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94783600.0
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13650800.0
14,NaN,NaN,68.998168,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.724165,117105600.0
15,NaN,NaN,55.580659,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.706161,-87314800.0
16,NaN,NaN,45.152359,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.695098,-253430800.0
17,NaN,NaN,46.541813,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-87.034392,-73.817889,2.684662,-96858800.0
18,NaN,NaN,37.470411,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-77.639159,-81.393239,2.635359,-299420400.0
19,NaN,NaN,35.398357,NaN,NaN,42.761509,41.213177,39.664845,41.213177,NaN,NaN,-61.987667,-75.553739,2.599702,-483613200.0
20,NaN,NaN,37.137797,NaN,NaN,42.849894,41.156085,39.462277,41.156085,NaN,NaN,-49.633849,-63.086892,2.602416,-353697600.0
21,NaN,NaN,38.494769,NaN,NaN,42.910288,41.103485,39.296682,41.103485,NaN,NaN,-41.626480,-51.082666,2.600383,-164774400.0
22,NaN,NaN,25.947938,NaN,NaN,43.228467,40.955378,38.682290,40.955378,NaN,NaN,-40.766048,-44.008793,2.560085,-511149600.0
23,NaN,NaN,21.743858,NaN,NaN,43.578808,40.736586,37.894365,40.736586,NaN,NaN,-38.059459,-40.150662,2.593452,-802103600.0
24,NaN,NaN,39.079735,NaN,NaN,43.590204,40.602782,37.615360,40.602782,NaN,NaN,-24.766595,-34.530701,2.689292,-529128400.0
25,NaN,NaN,34.666392,NaN,NaN,43.652099,40.427961,37.203823,40.427961,NaN,NaN,-14.972527,-25.932860,2.662138,-735562800.0
26,NaN,NaN,30.066740,NaN,NaN,43.790970,40.201723,36.612476,40.201723,NaN,NaN,-13.427890,-17.722337,2.652998,-953124800.0
27,NaN,NaN,34.135128,NaN,NaN,43.765508,39.986214,36.206921,39.986214,NaN,NaN,-15.615515,-14.671977,2.663105,-670434400.0
28,NaN,NaN,45.513623,NaN,NaN,43.544882,39.824081,36.103280,39.824081,NaN,NaN,-6.295029,-11.779478,2.747587,-427156400.0
29,NaN,NaN,48.015951,NaN,NaN,43.330502,39.691933,36.053364,39.691933,NaN,NaN,11.072670,-3.612625,2.734578,-296959600.0
30,NaN,NaN,52.392758,NaN,NaN,42.991933,39.561348,36.130763,39.561348,NaN,NaN,26.336916,10.371519,2.744682,-134380000.0
31,NaN,NaN,59.246581,NaN,NaN,42.753752,39.495572,36.237392,39.495572,NaN,NaN,41.539703,26.316430,2.801799,70208800.0
32,NaN,NaN,58.345183,NaN,NaN,42.524615,39.432606,36.340598,39.432606,NaN,NaN,51.997625,39.958082,2.790443,-90495600.0
33,-0.373864,-0.940885,57.371636,NaN,NaN,42.339137,39.380014,36.420891,39.380014,NaN,NaN,56.241818,49.926382,2.779393,-226217600.0
34,-0.274209,-0.807550,56.017961,NaN,NaN,42.113883,39.317692,36.521502,39.317692,NaN,NaN,52.331331,53.523591,2.776466,-376104000.0
35,-0.165930,-0.679226,57.975711,NaN,NaN,42.071541,39.305675,36.539808,39.305675,NaN,NaN,52.421489,53.664879,2.783937,-252136400.0
36,-0.022398,-0.547861,61.815823,NaN,NaN,42.278027,39.366024,36.454020,39.366024,NaN,NaN,56.395159,53.715993,2.796986,-116886800.0
37,0.156015,-0.407086,65.717870,NaN,NaN,42.641729,39.462826,36.283924,39.462826,NaN,NaN,62.381603,57.066084,2.825023,35762000.0
38,0.283037,-0.269061,64.530896,NaN,NaN,43.012922,39.594708,36.176494,39.594708,NaN,NaN,65.108391,61.295051,2.811690,-119950400.0
39,0.374218,-0.140405,63.951811,NaN,NaN,43.346790,39.735087,36.123384,39.735087,NaN,NaN,64.319995,63.936663,2.811643,-271078800.0
40,0.382314,-0.035861,57.527347,NaN,NaN,43.527908,39.833000,36.138092,39.833000,NaN,NaN,59.272797,62.900394,2.801177,-466286800.0
41,0.407212,0.052754,59.237616,NaN,NaN,43.735167,39.941136,36.147106,39.941136,NaN,NaN,52.309091,58.633961,2.782214,-312470800.0
42,0.433629,0.128929,60.109639,NaN,NaN,43.918540,40.142563,36.366586,40.142563,NaN,NaN,42.550513,51.377467,2.769805,-198865200.0
43,0.446543,0.192451,59.770996,NaN,NaN,43.949840,40.389609,36.829378,40.389609,NaN,40.596321,34.223099,43.027568,2.757047,-294019200.0
44,0.420518,0.238065,56.052856,4.051322,0.823532,44.028293,40.539886,37.051479,40.539886,NaN,40.638547,12.020126,29.597913,2.704886,-420833200.0

In [41]:
indicators_with_price = pd.concat([indicators, stock_data["Adj Close"]], axis=1, join='inner')
indicators_with_price.head(45)

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102223600.0,40.722878
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-15848000.0,40.715790
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73890400.0,40.904911
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168530400.0,41.370628
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86259200.0,41.216953
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-76800.0,41.212234
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-95916400.0,41.202774
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-21245600.0,41.436813
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80426800.0,41.864700
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-37836800.0,41.651932
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99710400.0,42.339878
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,224484000.0,42.377705
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94783600.0,42.188576
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13650800.0,41.843426
14,NaN,NaN,68.998168,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.724165,117105600.0,41.852882
15,NaN,NaN,55.580659,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.706161,-87314800.0,41.186226
16,NaN,NaN,45.152359,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.695098,-253430800.0,40.451008
17,NaN,NaN,46.541813,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-87.034392,-73.817889,2.684662,-96858800.0,40.545582
18,NaN,NaN,37.470411,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-77.639159,-81.393239,2.635359,-299420400.0,39.706341
19,NaN,NaN,35.398357,NaN,NaN,42.761509,41.213177,39.664845,41.213177,NaN,NaN,-61.987667,-75.553739,2.599702,-483613200.0,39.472301
20,NaN,NaN,37.137797,NaN,NaN,42.849894,41.156085,39.462277,41.156085,NaN,NaN,-49.633849,-63.086892,2.602416,-353697600.0,39.581047
21,NaN,NaN,38.494769,NaN,NaN,42.910288,41.103485,39.296682,41.103485,NaN,NaN,-41.626480,-51.082666,2.600383,-164774400.0,39.663788
22,NaN,NaN,25.947938,NaN,NaN,43.228467,40.955378,38.682290,40.955378,NaN,NaN,-40.766048,-44.008793,2.560085,-511149600.0,37.942772
23,NaN,NaN,21.743858,NaN,NaN,43.578808,40.736586,37.894365,40.736586,NaN,NaN,-38.059459,-40.150662,2.593452,-802103600.0,36.994785
24,NaN,NaN,39.079735,NaN,NaN,43.590204,40.602782,37.615360,40.602782,NaN,NaN,-24.766595,-34.530701,2.689292,-529128400.0,38.540871
25,NaN,NaN,34.666392,NaN,NaN,43.652099,40.427961,37.203823,40.427961,NaN,NaN,-14.972527,-25.932860,2.662138,-735562800.0,37.715820
26,NaN,NaN,30.066740,NaN,NaN,43.790970,40.201723,36.612476,40.201723,NaN,NaN,-13.427890,-17.722337,2.652998,-953124800.0,36.678009
27,NaN,NaN,34.135128,NaN,NaN,43.765508,39.986214,36.206921,39.986214,NaN,NaN,-15.615515,-14.671977,2.663105,-670434400.0,37.126637
28,NaN,NaN,45.513623,NaN,NaN,43.544882,39.824081,36.103280,39.824081,NaN,NaN,-6.295029,-11.779478,2.747587,-427156400.0,38.622044
29,NaN,NaN,48.015951,NaN,NaN,43.330502,39.691933,36.053364,39.691933,NaN,NaN,11.072670,-3.612625,2.734578,-296959600.0,39.008961
30,NaN,NaN,52.392758,NaN,NaN,42.991933,39.561348,36.130763,39.561348,NaN,NaN,26.336916,10.371519,2.744682,-134380000.0,39.728180
31,NaN,NaN,59.246581,NaN,NaN,42.753752,39.495572,36.237392,39.495572,NaN,NaN,41.539703,26.316430,2.801799,70208800.0,41.062187
32,NaN,NaN,58.345183,NaN,NaN,42.524615,39.432606,36.340598,39.432606,NaN,NaN,51.997625,39.958082,2.790443,-90495600.0,40.929256
33,-0.373864,-0.940885,57.371636,NaN,NaN,42.339137,39.380014,36.420891,39.380014,NaN,NaN,56.241818,49.926382,2.779393,-226217600.0,40.791584
34,-0.274209,-0.807550,56.017961,NaN,NaN,42.113883,39.317692,36.521502,39.317692,NaN,NaN,52.331331,53.523591,2.776466,-376104000.0,40.606445
35,-0.165930,-0.679226,57.975711,NaN,NaN,42.071541,39.305675,36.539808,39.305675,NaN,NaN,52.421489,53.664879,2.783937,-252136400.0,40.945877
36,-0.022398,-0.547861,61.815823,NaN,NaN,42.278027,39.366024,36.454020,39.366024,NaN,NaN,56.395159,53.715993,2.796986,-116886800.0,41.657986
37,0.156015,-0.407086,65.717870,NaN,NaN,42.641729,39.462826,36.283924,39.462826,NaN,NaN,62.381603,57.066084,2.825023,35762000.0,42.481636
38,0.283037,-0.269061,64.530896,NaN,NaN,43.012922,39.594708,36.176494,39.594708,NaN,NaN,65.108391,61.295051,2.811690,-119950400.0,42.343971
39,0.374218,-0.140405,63.951811,NaN,NaN,43.346790,39.735087,36.123384,39.735087,NaN,NaN,64.319995,63.936663,2.811643,-271078800.0,42.279884
40,0.382314,-0.035861,57.527347,NaN,NaN,43.527908,39.833000,36.138092,39.833000,NaN,NaN,59.272797,62.900394,2.801177,-466286800.0,41.539303
41,0.407212,0.052754,59.237616,NaN,NaN,43.735167,39.941136,36.147106,39.941136,NaN,NaN,52.309091,58.633961,2.782214,-312470800.0,41.826519
42,0.433629,0.128929,60.109639,NaN,NaN,43.918540,40.142563,36.366586,40.142563,NaN,NaN,42.550513,51.377467,2.769805,-198865200.0,41.971306
43,0.446543,0.192451,59.770996,NaN,NaN,43.949840,40.389609,36.829378,40.389609,NaN,40.596321,34.223099,43.027568,2.757047,-294019200.0,41.935699
44,0.420518,0.238065,56.052856,4.051322,0.823532,44.028293,40.539886,37.051479,40.539886,NaN,40.638547,12.020126,29.597913,2.704886,-420833200.0,41.546410

In [42]:
indicators_with_price = indicators_with_price.dropna()
indicators_with_price = indicators_with_price.reset_index(drop=True)
indicators_with_price

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close
0,0.567014,0.443929,58.241527,7.100792,1.143600,43.382888,41.728834,40.074780,41.728834,40.814299,41.035721,-7.013330,-3.909606,2.715222,-3.124152e+08,42.355835
1,0.548494,0.464842,58.592094,7.332800,1.202904,43.261031,41.862708,40.464386,41.862708,40.847955,41.096608,-20.016706,-8.448319,2.714432,-2.214400e+08,42.405678
2,0.515805,0.475035,57.044809,6.516152,0.819328,43.280287,41.922406,40.564525,41.922406,40.878762,41.148143,-27.992068,-18.340701,2.690138,-3.790588e+08,42.256142
3,0.432812,0.466590,50.806424,3.052123,-0.254189,43.245417,41.956469,40.667521,41.956469,40.892874,41.168692,-36.985407,-28.331394,2.648797,-5.128460e+08,41.610512
4,0.361721,0.445616,50.674720,2.976500,-0.055668,43.183914,41.996703,40.809492,41.996703,40.897387,41.187696,-46.752088,-37.243188,2.644561,-5.914436e+08,41.596264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1470,-1.918426,-1.197745,36.736038,-3.771153,-3.720001,199.131030,188.796999,178.462968,188.796999,189.292038,187.549134,26.310155,30.750307,3.101382,3.547580e+09,182.679993
1471,-1.555397,-1.269276,51.604604,4.598480,3.830002,198.242596,188.434000,178.625403,188.434000,189.536287,187.597173,33.195313,30.241850,3.341284,3.625586e+09,188.630005
1472,-1.019515,-1.219324,56.967975,8.324259,4.119995,197.297528,188.164999,179.032471,188.164999,189.787603,187.773298,51.916516,37.140661,3.339763,3.694327e+09,191.559998
1473,-0.402178,-1.055894,60.698088,11.147862,5.880005,197.121605,188.117999,179.114394,188.117999,190.033787,188.045152,76.309536,53.807122,3.370495,3.754460e+09,193.889999
1474,0.188980,-0.806919,62.629499,12.671634,5.469986,197.221811,188.142999,179.064188,188.142999,190.284400,188.362256,88.961635,72.395896,3.266888,3.796816e+09,195.179993

In [43]:
# Irrelelvant
indicators_with_price['Prev_Adj_Close'] = indicators_with_price['Adj Close'].shift(1)
indicators_with_price['Return'] = ((indicators_with_price['Adj Close'] - indicators_with_price['Prev_Adj_Close'])/indicators_with_price['Prev_Adj_Close'])*100
indicators_with_price['Signal'] = np.where(indicators_with_price['Return'] > 1, 1,
                                           np.where(indicators_with_price['Return'] < -1, 2, 0))
indicators_with_price

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close,Prev_Adj_Close,Return,Signal
0,0.567014,0.443929,58.241527,7.100792,1.143600,43.382888,41.728834,40.074780,41.728834,40.814299,41.035721,-7.013330,-3.909606,2.715222,-3.124152e+08,42.355835,NaN,NaN,0
1,0.548494,0.464842,58.592094,7.332800,1.202904,43.261031,41.862708,40.464386,41.862708,40.847955,41.096608,-20.016706,-8.448319,2.714432,-2.214400e+08,42.405678,42.355835,0.117676,0
2,0.515805,0.475035,57.044809,6.516152,0.819328,43.280287,41.922406,40.564525,41.922406,40.878762,41.148143,-27.992068,-18.340701,2.690138,-3.790588e+08,42.256142,42.405678,-0.352632,0
3,0.432812,0.466590,50.806424,3.052123,-0.254189,43.245417,41.956469,40.667521,41.956469,40.892874,41.168692,-36.985407,-28.331394,2.648797,-5.128460e+08,41.610512,42.256142,-1.527896,2
4,0.361721,0.445616,50.674720,2.976500,-0.055668,43.183914,41.996703,40.809492,41.996703,40.897387,41.187696,-46.752088,-37.243188,2.644561,-5.914436e+08,41.596264,41.610512,-0.034241,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1470,-1.918426,-1.197745,36.736038,-3.771153,-3.720001,199.131030,188.796999,178.462968,188.796999,189.292038,187.549134,26.310155,30.750307,3.101382,3.547580e+09,182.679993,183.630005,-0.517351,0
1471,-1.555397,-1.269276,51.604604,4.598480,3.830002,198.242596,188.434000,178.625403,188.434000,189.536287,187.597173,33.195313,30.241850,3.341284,3.625586e+09,188.630005,182.679993,3.257068,1
1472,-1.019515,-1.219324,56.967975,8.324259,4.119995,197.297528,188.164999,179.032471,188.164999,189.787603,187.773298,51.916516,37.140661,3.339763,3.694327e+09,191.559998,188.630005,1.553301,1
1473,-0.402178,-1.055894,60.698088,11.147862,5.880005,197.121605,188.117999,179.114394,188.117999,190.033787,188.045152,76.309536,53.807122,3.370495,3.754460e+09,193.889999,191.559998,1.216330,1
1474,0.188980,-0.806919,62.629499,12.671634,5.469986,197.221811,188.142999,179.064188,188.142999,190.284400,188.362256,88.961635,72.395896,3.266888,3.796816e+09,195.179993,193.889999,0.665322,0

In [44]:
# Not important
indicators_with_price["Signal"].value_counts()

Signal
0    737
1    414
2    324
Name: count, dtype: int64

In [45]:
indicators_with_price.dropna(inplace=True)
indicators_with_price

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close,Prev_Adj_Close,Return,Signal
1,0.548494,0.464842,58.592094,7.332800,1.202904,43.261031,41.862708,40.464386,41.862708,40.847955,41.096608,-20.016706,-8.448319,2.714432,-2.214400e+08,42.405678,42.355835,0.117676,0
2,0.515805,0.475035,57.044809,6.516152,0.819328,43.280287,41.922406,40.564525,41.922406,40.878762,41.148143,-27.992068,-18.340701,2.690138,-3.790588e+08,42.256142,42.405678,-0.352632,0
3,0.432812,0.466590,50.806424,3.052123,-0.254189,43.245417,41.956469,40.667521,41.956469,40.892874,41.168692,-36.985407,-28.331394,2.648797,-5.128460e+08,41.610512,42.256142,-1.527896,2
4,0.361721,0.445616,50.674720,2.976500,-0.055668,43.183914,41.996703,40.809492,41.996703,40.897387,41.187696,-46.752088,-37.243188,2.644561,-5.914436e+08,41.596264,41.610512,-0.034241,0
5,0.226727,0.401838,42.776469,-1.895769,-1.685963,43.175299,41.999076,40.822854,41.999076,40.886126,41.163972,-59.960169,-47.899222,2.611109,-7.396632e+08,40.653915,41.596264,-2.265464,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1470,-1.918426,-1.197745,36.736038,-3.771153,-3.720001,199.131030,188.796999,178.462968,188.796999,189.292038,187.549134,26.310155,30.750307,3.101382,3.547580e+09,182.679993,183.630005,-0.517351,0
1471,-1.555397,-1.269276,51.604604,4.598480,3.830002,198.242596,188.434000,178.625403,188.434000,189.536287,187.597173,33.195313,30.241850,3.341284,3.625586e+09,188.630005,182.679993,3.257068,1
1472,-1.019515,-1.219324,56.967975,8.324259,4.119995,197.297528,188.164999,179.032471,188.164999,189.787603,187.773298,51.916516,37.140661,3.339763,3.694327e+09,191.559998,188.630005,1.553301,1
1473,-0.402178,-1.055894,60.698088,11.147862,5.880005,197.121605,188.117999,179.114394,188.117999,190.033787,188.045152,76.309536,53.807122,3.370495,3.754460e+09,193.889999,191.559998,1.216330,1
1474,0.188980,-0.806919,62.629499,12.671634,5.469986,197.221811,188.142999,179.064188,188.142999,190.284400,188.362256,88.961635,72.395896,3.266888,3.796816e+09,195.179993,193.889999,0.665322,0

In [46]:
indicators_with_price.columns

Index(['MACD', 'MACD_signal', 'RSI', 'CMO', 'MOM', 'Upper_BB', 'Middle_BB',
       'Lower_BB', 'SMA_SHORT', 'SMA_LONG', 'EMA', 'SLOWK', 'SLOWD', 'ATR',
       'OBV', 'Adj Close', 'Prev_Adj_Close', 'Return', 'Signal'],
      dtype='object')

In [47]:
# indicators_with_price = indicators_with_price.drop(columns=['Next_Adj_Close', 'Return'])
# indicators_with_price

In [48]:
indicators_with_price.drop(columns=['Prev_Adj_Close', "Signal"], inplace=True)
indicators_with_price.head(50)

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close,Return
1,0.548494,0.464842,58.592094,7.332800,1.202904,43.261031,41.862708,40.464386,41.862708,40.847955,41.096608,-20.016706,-8.448319,2.714432,-2.214400e+08,42.405678,0.117676
2,0.515805,0.475035,57.044809,6.516152,0.819328,43.280287,41.922406,40.564525,41.922406,40.878762,41.148143,-27.992068,-18.340701,2.690138,-3.790588e+08,42.256142,-0.352632
3,0.432812,0.466590,50.806424,3.052123,-0.254189,43.245417,41.956469,40.667521,41.956469,40.892874,41.168692,-36.985407,-28.331394,2.648797,-5.128460e+08,41.610512,-1.527896
4,0.361721,0.445616,50.674720,2.976500,-0.055668,43.183914,41.996703,40.809492,41.996703,40.897387,41.187696,-46.752088,-37.243188,2.644561,-5.914436e+08,41.596264,-0.034241
5,0.226727,0.401838,42.776469,-1.895769,-1.685963,43.175299,41.999076,40.822854,41.999076,40.886126,41.163972,-59.960169,-47.899222,2.611109,-7.396632e+08,40.653915,-2.265464
6,0.072555,0.335982,38.805928,-4.708064,-2.298222,43.330935,41.955757,40.580579,41.955757,40.863471,41.115772,-60.364782,-55.692347,2.604321,-9.056264e+08,40.079483,-1.412982
7,-0.123099,0.244166,33.410024,-9.019895,-3.037197,43.669844,41.830426,39.991009,41.830426,40.822443,41.028466,-57.037889,-59.120947,2.589764,-1.069742e+09,39.151379,-2.315660
8,-0.126722,0.169988,48.771937,0.230770,-0.833458,43.603899,41.756843,39.909787,41.756843,40.813906,41.027644,-35.113303,-50.838658,2.699325,-9.195768e+08,41.009968,4.747187
9,-0.212000,0.093590,42.761391,-4.462404,-1.894451,43.620650,41.637566,39.654482,41.637566,40.775781,40.980123,-25.755924,-39.302372,2.704911,-1.083267e+09,39.958431,-2.564100
10,-0.311617,0.012549,40.504319,-6.346442,-1.669304,43.661175,41.499418,39.337661,41.499418,40.733080,40.915092,-23.129894,-27.999707,2.693601,-1.249941e+09,39.516922,-1.104921
11,-0.361498,-0.062260,42.777713,-4.867431,-0.625504,43.694934,41.413728,39.132522,41.413728,40.682793,40.866666,-31.638972,-26.841597,2.745528,-1.096347e+09,39.825504,0.780886
12,-0.417287,-0.133266,41.338390,-5.999296,-0.981174,43.709491,41.300622,38.891754,41.300622,40.626527,40.808788,-33.349931,-29.372932,2.721526,-1.246694e+09,39.564407,-0.655602
13,-0.423862,-0.191385,44.466516,-4.030440,0.263954,43.655485,41.200572,38.745659,41.200572,40.582161,40.771522,-30.537671,-31.842191,2.714495,-1.125582e+09,39.970295,1.025891
14,-0.363211,-0.225750,49.885840,-0.435816,1.262314,43.579270,41.140518,38.701765,41.140518,40.559985,40.769881,-23.649220,-29.178941,2.737188,-9.871604e+08,40.734615,1.912221
15,-0.289020,-0.238404,51.759523,0.859683,1.436047,43.546090,41.114052,38.682014,41.114052,40.543269,40.780868,-13.681330,-22.622740,2.743309,-8.794276e+08,41.017094,0.693460
16,-0.311294,-0.252982,45.025963,-3.853638,0.304134,43.457727,41.012458,38.567190,41.012458,40.518903,40.744738,-15.941614,-17.757388,2.697566,-1.019449e+09,39.967922,-2.557888
17,-0.293577,-0.261101,47.789592,-2.010649,2.421547,43.223493,40.894605,38.565718,40.894605,40.517170,40.727830,-20.849073,-16.824006,2.740924,-9.033780e+08,40.364319,0.991787
18,-0.215757,-0.252032,52.696835,1.419529,4.129108,42.889424,40.794080,38.698735,40.794080,40.528736,40.745433,-19.855429,-18.882039,2.769121,-7.897436e+08,41.123894,1.881798
19,-0.167665,-0.235159,51.380450,0.543878,2.390762,42.607663,40.704711,38.801758,40.704711,40.553242,40.753708,-10.385327,-17.029943,2.739620,-8.794700e+08,40.931633,-0.467516
20,-0.095886,-0.207304,53.978894,2.354463,3.619331,42.427108,40.653676,38.880245,40.653676,40.590499,40.779550,0.476623,-9.921377,2.745245,-7.879128e+08,41.335152,0.985836
21,-0.027384,-0.171320,54.880196,2.981715,4.797192,42.237330,40.607153,38.976975,40.607153,40.628382,40.810468,4.591475,-1.772409,2.736645,-6.874156e+08,41.475201,0.338813
22,0.047238,-0.127609,56.572402,4.145771,4.607307,42.118850,40.581043,39.043235,40.581043,40.669785,40.851512,13.924927,6.331009,2.724906,-6.011020e+08,41.733944,0.623851
23,0.150987,-0.071889,60.146029,6.689107,3.686329,42.272666,40.615936,38.959206,40.615936,40.757097,40.916261,22.180931,13.565778,2.744631,-4.946804e+08,42.308372,1.376406
24,0.222978,-0.012916,59.277731,6.212456,3.204464,42.395831,40.646794,38.897757,40.646794,40.861470,40.973913,28.084619,21.396826,2.719774,-5.776984e+08,42.213425,-0.224419
25,0.181406,0.025948,49.567871,0.427698,1.288914,42.421434,40.664953,38.908472,40.664953,40.910994,40.975832,20.146415,23.470655,2.642224,-7.169336e+08,41.017094,-2.834006
26,0.012705,0.023300,39.724036,-6.863810,-1.725662,42.461952,40.627805,38.793658,40.627805,40.943408,40.902974,-8.290739,13.313432,2.581201,-9.788980e+08,39.336525,-4.097240
27,-0.128701,-0.007100,39.156300,-7.330555,-1.706665,42.454276,40.631365,38.808455,40.631365,40.994300,40.828290,-34.549878,-7.564734,2.567792,-1.124960e+09,39.222591,-0.289638
28,-0.281574,-0.061995,36.466801,-9.553028,-2.114937,42.515718,40.514699,38.513681,40.514699,41.025300,40.732661,-45.877152,-29.572590,2.552943,-1.259728e+09,38.676647,-1.391913
29,-0.384693,-0.126535,37.885133,-8.729348,-1.761269,42.577351,40.459037,38.340722,40.459037,41.029763,40.648773,-39.397624,-39.941551,2.561901,-1.146200e+09,38.845177,0.435740
30,-0.450308,-0.191289,39.061220,-8.061965,-1.965412,42.610309,40.432214,38.254119,40.432214,41.029193,40.574626,-33.203249,-39.492675,2.563717,-1.034348e+09,38.980465,0.348276
31,-0.532561,-0.259544,36.575112,-9.947413,-3.128510,42.686413,40.367412,38.048412,40.367412,41.005219,40.483731,-32.806053,-35.135642,2.530740,-1.176971e+09,38.529476,-1.156961
32,-0.535265,-0.314688,42.657019,-6.489523,-3.254303,42.697390,40.350559,38.003727,40.350559,40.968522,40.427891,-28.595159,-31.534820,2.584653,-1.007261e+09,39.227333,1.811229
33,-0.458572,-0.343465,49.472304,-2.193909,-2.205139,42.701501,40.358986,38.016470,40.358986,40.952713,40.415044,-18.764702,-26.721971,2.619511,-7.929836e+08,40.138832,2.323632
34,-0.251812,-0.325134,59.545016,5.401848,-0.367916,42.852530,40.417853,37.983176,40.417853,40.975121,40.481574,5.866593,-13.831089,2.739451,-5.268260e+08,41.911968,4.417508
35,-0.080893,-0.276286,59.913625,5.709010,0.448612,42.984216,40.466394,37.948572,40.466394,41.002750,40.548522,25.969140,4.357010,2.719706,-3.905532e+08,41.987915,0.181206
36,0.185352,-0.183958,66.948322,12.047572,1.808735,43.506958,40.649761,37.792564,40.649761,41.056538,40.685710,45.736776,25.857503,2.816483,-1.657480e+08,43.635254,3.923364
37,0.417020,-0.063763,68.103523,13.191891,1.979641,44.022555,40.829092,37.635629,40.829092,41.102397,40.830832,51.666111,41.124009,2.849752,4.057600e+06,43.950947,0.723481
38,0.610627,0.071115,68.887241,13.958481,2.226517,44.489634,40.981008,37.472383,40.981008,41.136009,40.978893,58.084165,51.829018,2.832202,1.176688e+08,44.162216,0.480694
39,0.780159,0.212924,70.053507,15.087776,2.926754,44.982163,41.158085,37.334007,41.158085,41.178592,41.134194,59.732870,56.494382,2.821887,2.105136e+08,44.473164,0.704103
40,0.954839,0.361307,72.337999,17.358399,3.109509,45.541703,41.346792,37.151882,41.346792,41.235181,41.310866,63.227911,60.348315,2.843133,3.224708e+08,45.109299,1.430380
41,1.067130,0.502472,70.770088,16.498745,2.216370,45.997986,41.519920,37.041853,41.519920,41.303150,41.472060,64.912077,62.624286,2.811888,2.176220e+08,44.937748,-0.380300
42,1.134581,0.628893,69.774538,15.967426,1.698479,46.380505,41.674867,36.969228,41.674867,41.363277,41.621430,64.592842,64.244277,2.785664,1.345068e+08,44.832886,-0.233350
43,1.141994,0.731514,65.895509,13.901954,1.706406,46.631601,41.780719,36.929837,41.780719,41.412359,41.746052,61.526820,63.677246,2.724875,3.972600e+07,44.425423,-0.908849
44,1.167862,0.818783,67.853887,15.469564,2.484203,46.941613,41.912050,36.882487,41.912050,41.470446,41.883563,61.088758,62.402807,2.722354,1.164584e+08,44.840038,0.933285
45,1.152200,0.885467,65.100640,14.016823,2.150806,47.228052,42.089019,36.949987,42.089019,41.530648,42.002359,59.272293,60.629290,2.698433,4.728240e+07,44.556484,-0.632368
46,1.113874,0.931148,63.514699,13.184200,2.138313,47.411589,42.341916,37.272243,42.341916,41.578541,42.108675,56.482962,58.948004,2.676831,-2.590840e+07,44.394455,-0.363649
47,1.096243,0.964167,65.282768,14.425497,3.098473,47.573568,42.616236,37.658903,42.616236,41.618293,42.224244,45.620369,53.791875,2.694418,4.769480e+07,44.708984,0.708488
48,1.061003,0.983534,64.091817,13.832500,3.000729,47.592557,42.912253,38.231948,42.912253,41.647545,42.329699,34.736756,45.613362,2.681318,-1.326800e+07,44.596992,-0.250491
49,1.044112,0.995650,65.806972,14.983573,4.229015,47.574094,43.214141,38.854187,43.214141,41.690823,42.443176,22.112270,34.156465,2.670367,6.696560e+07,44.882931,0.641160
50,1.014987,0.999517,65.219804,14.709144,4.753403,47.457199,43.506762,39.556324,43.506762,41.740364,42.549386,-9.602725,15.748767,2.645846,-2.597040e+07,44.832886,-0.111501

In [49]:
y = indicators_with_price["Return"]
y_2 = indicators_with_price["SMA_SHORT"]
y_3 = indicators_with_price["EMA"]
y_4 = indicators_with_price["Upper_BB"]
y_5 = indicators_with_price["Middle_BB"]
y_6 = indicators_with_price["Lower_BB"]
X = np.array(date)

trace = go.Scatter(x=X, y=y, mode="lines", name="Adj Close")
trace_2 = go.Scatter(x=X, y=y_2, mode="lines", name="SMA")
trace_3 = go.Scatter(x=X, y=y_3, mode="lines", name="EMA")
trace_4 = go.Scatter(x=X, y=y_4, mode="lines", name="Upper_BB")
trace_5 = go.Scatter(x=X, y=y_5, mode="lines", name="Middle_BB")
trace_6 = go.Scatter(x=X, y=y_6, mode="lines", name="Lower_BB")



layout = go.Layout(
    title='Stock Price and Volume',
    xaxis=dict(title='Date'),
    yaxis=dict(title='Adj Close', side='left', rangemode='tozero'),
    yaxis2=dict(title='SMA', side='right', overlaying='y', rangemode='tozero'),
    yaxis3=dict(title='EMA', side='right', overlaying='y', rangemode='tozero'),
    yaxis4=dict(title='Upper_BB', side='right', overlaying='y', rangemode='tozero'),
    yaxis5=dict(title='Middle_BB', side='right', overlaying='y', rangemode='tozero'),
    yaxis6=dict(title='Lower_BB', side='right', overlaying='y', rangemode='tozero'),
    height=600,
)

fig = go.Figure(data=[trace, trace_2, trace_3, trace_4, trace_5, trace_6], layout=layout)

# Show plot
pyo.iplot(fig)

In [50]:
# Custom Dataset
class RollingWindowDataset(Dataset):
    def __init__(self, X, y, window_size, device="gpu"):
        self.X = X.clone().detach().to(torch.float).to(device)
        self.y = y.clone().detach().to(torch.float).to(device)
        self.window_size = window_size

    def __len__(self):
        # Adjust the length to account for window size
        return len(self.X) - self.window_size 

    def __getitem__(self, idx):
        # Ensure idx is within the valid range
        if idx + self.window_size > len(self.X):
            raise IndexError("Index out of bounds")

        X_window = self.X[idx : idx + self.window_size]
        
        y_target = self.y[idx + self.window_size]  

        return X_window.clone().detach().to(torch.float), y_target.clone().detach().to(torch.float)

In [51]:
X = indicators_with_price.iloc[:,:-1]
y = indicators_with_price.iloc[:,-2]

signal_true = indicators_with_price.iloc[:,-1]
y

1        42.405678
2        42.256142
3        41.610512
4        41.596264
5        40.653915
           ...
1470    182.679993
1471    188.630005
1472    191.559998
1473    193.889999
1474    195.179993
Name: Adj Close, Length: 1474, dtype: float64

In [52]:
train_signal_true = signal_true.iloc[:int(len(X)*0.8)]
test_signal_true = signal_true.iloc[int(len(X)*0.8):]
test_signal_true

1180    1.297136
1181    0.378186
1182   -2.168029
1183    1.466111
1184    0.592644
          ...
1470   -0.517351
1471    3.257068
1472    1.553301
1473    1.216330
1474    0.665322
Name: Return, Length: 295, dtype: float64

In [53]:
correlation_matrix = X.corr()

# Perform hierarchical clustering to find the order of features
linked = sch.linkage(sch.distance.pdist(correlation_matrix), method='ward')
cluster_order = sch.dendrogram(linked, no_plot=True)['leaves']

# Reorder the correlation matrix
correlation_matrix_ordered = correlation_matrix.iloc[cluster_order, cluster_order]

fig = go.Figure(data=go.Heatmap(
                    z=correlation_matrix_ordered,
                    x=correlation_matrix_ordered.columns,
                    y=correlation_matrix_ordered.columns,
                    colorscale='Viridis',
                    text=correlation_matrix_ordered.round(2).values,  
                    texttemplate="%{text}",
                    textfont={"size":9}  
                    ))

# Update the layout
fig.update_layout(
    title='Ordered Correlation Matrix',
    xaxis_title="Variables",
    yaxis_title="Variables",
    xaxis=dict(side='bottom'),
    yaxis=dict(autorange='reversed'),
    width=1000,  
    height=1000,  
)

# Show the figure
pyo.iplot(fig)

In [54]:
X= X.iloc[:, cluster_order]

In [55]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

y_test.head(44)

1180    149.882233
1181    150.449066
1182    147.187286
1183    149.345215
1184    150.230301
1185    147.286728
1186    143.418365
1187    140.385315
1188    147.207169
1189    147.485626
1190    146.988403
1191    145.814987
1192    142.115631
1193    140.156586
1194    141.857086
1195    141.369812
1196    143.686859
1197    144.661423
1198    142.413971
1199    135.741272
1200    133.762329
1201    131.634232
1202    131.564636
1203    134.697128
1204    131.494995
1205    131.127045
1206    129.307251
1207    125.339417
1208    128.889572
1209    129.207794
1210    124.374802
1211    125.657639
1212    124.325081
1213    128.899521
1214    129.426575
1215    130.003342
1216    132.748016
1217    132.668457
1218    134.010925
1219    135.184372
1220    134.458450
1221    134.518112
1222    137.103668
1223    140.325653
Name: Adj Close, dtype: float64

In [56]:
X_train_df = pd.DataFrame()
X_test_df = pd.DataFrame()
scaler_dict = {}

X_train_df = X_train
X_test_df = X_test

for column in X_train.columns:

    if column not in ["Adj Close", "Return"]:
        scaler = MinMaxScaler()

        X_train_scaled = scaler.fit_transform(X_train[[column]].values)
        X_train_df[column] = X_train_scaled
            
        X_test_scaled = scaler.transform(X_test[[column]].values)
        X_test_df[column] = X_test_scaled

        scaler_dict[column] = scaler


X_train_df.head(24)

features = X_train_df.columns
X_train_df

,ATR,OBV,Adj Close,Lower_BB,Upper_BB,Middle_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,MACD,MACD_signal,MOM,RSI,CMO
1,0.177936,0.261686,42.405678,0.048691,0.032213,0.037797,0.037797,0.016755,0.014072,0.483866,0.507174,0.508804,0.493383,0.498961,0.567548,0.468235
2,0.172548,0.234481,42.256142,0.049438,0.032346,0.038231,0.038231,0.016988,0.014472,0.447234,0.458578,0.506461,0.494198,0.494287,0.542886,0.458079
3,0.163379,0.211390,41.610512,0.050206,0.032106,0.038478,0.038478,0.017095,0.014632,0.405927,0.409499,0.500513,0.493523,0.481206,0.443456,0.415000
4,0.162440,0.197825,41.596264,0.051265,0.031682,0.038770,0.038770,0.017129,0.014780,0.361068,0.365720,0.495417,0.491846,0.483625,0.441356,0.414059
5,0.155021,0.172243,40.653915,0.051365,0.031623,0.038787,0.038787,0.017044,0.014595,0.300402,0.313373,0.485741,0.488346,0.463760,0.315470,0.353466
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1175,0.850805,0.753803,146.053635,0.738088,0.800862,0.778358,0.778358,0.818604,0.829435,0.680158,0.631198,0.340107,0.343542,0.360230,0.463732,0.349553
1176,0.849089,0.770024,148.867889,0.744000,0.803314,0.782527,0.782527,0.817400,0.830427,0.747328,0.665569,0.388138,0.347930,0.321213,0.506322,0.377028
1177,0.803297,0.757360,147.455780,0.746416,0.805266,0.784731,0.784731,0.816305,0.830887,0.835637,0.739664,0.418622,0.358240,0.420018,0.480797,0.363378
1178,0.812803,0.772871,149.206024,0.747900,0.808367,0.787087,0.787087,0.815668,0.831932,0.856512,0.802536,0.453092,0.374178,0.423562,0.508857,0.380640
1179,0.765326,0.761787,147.962952,0.749683,0.810260,0.788953,0.788953,0.814627,0.832500,0.850520,0.839325,0.473178,0.391410,0.443981,0.484406,0.368318

In [57]:
scaler_adj = MinMaxScaler()
scaler_adj.fit(X_train[["Adj Close"]].values)

X_train_df['Adj Close'] = scaler_adj.transform(X_train[['Adj Close']].values).flatten()
X_test_df['Adj Close'] = scaler_adj.transform(X_test[['Adj Close']].values).flatten()

y_train = scaler_adj.transform(y_train.values.reshape(-1,1)).flatten()
y_test = scaler_adj.transform(y_test.values.reshape(-1,1)).flatten()



X_test_df

,ATR,OBV,Adj Close,Lower_BB,Upper_BB,Middle_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,MACD,MACD_signal,MOM,RSI,CMO
1180,0.764804,0.775662,0.793797,0.751875,0.813419,0.791684,0.791684,0.814103,0.833706,0.876576,0.853920,0.499847,0.411144,0.487570,0.517394,0.387564
1181,0.724522,0.788577,0.797684,0.752021,0.816205,0.793223,0.793223,0.813227,0.835055,0.895160,0.867699,0.523637,0.432238,0.448749,0.527281,0.393265
1182,0.685712,0.778442,0.775317,0.751879,0.815520,0.792793,0.792793,0.810946,0.835217,0.907286,0.887937,0.523008,0.448973,0.379730,0.456307,0.359880
1183,0.661729,0.787383,0.790114,0.752318,0.813808,0.792104,0.792104,0.810434,0.836117,0.913913,0.901248,0.534244,0.464868,0.444493,0.497611,0.382099
1184,0.623617,0.797445,0.796184,0.752139,0.815320,0.792815,0.792815,0.809834,0.837282,0.923475,0.911342,0.547370,0.480511,0.467133,0.514479,0.391192
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1470,0.263755,0.912203,1.018693,1.078159,1.105702,1.104494,1.104494,1.140327,1.152418,0.696649,0.699736,0.331987,0.360467,0.438975,0.219194,0.330144
1471,0.316961,0.925666,1.059493,1.079371,1.099583,1.101858,1.101858,1.142176,1.152792,0.728273,0.697238,0.358007,0.354748,0.530972,0.456177,0.434231
1472,0.316624,0.937531,1.079584,1.082407,1.093074,1.099905,1.099905,1.144078,1.154161,0.814261,0.731128,0.396416,0.358741,0.534505,0.541662,0.480565
1473,0.323439,0.947909,1.095561,1.083019,1.091863,1.099564,1.099564,1.145941,1.156274,0.926300,0.813001,0.440664,0.371807,0.555951,0.601114,0.515680
1474,0.300461,0.955220,1.104406,1.082644,1.092553,1.099746,1.099746,1.147838,1.158738,0.984412,0.904318,0.483036,0.391711,0.550955,0.631898,0.534631

In [58]:
correlation_matrix = X_train_df.corr()

# Create the heatmap with text
fig = go.Figure(data=go.Heatmap(
                    z=correlation_matrix,
                    x=correlation_matrix.columns,
                    y=correlation_matrix.columns,
                    colorscale='Viridis',
                    text=correlation_matrix.round(2).values,  # Rounded values for display
                    texttemplate="%{text}",
                    textfont={"size":9}  # Adjust text size if necessary
                    ))

# Update the layout
fig.update_layout(
    title='Correlation Matrix',
    xaxis_title="Variables",
    yaxis_title="Variables",
    xaxis=dict(side='bottom'),
    yaxis=dict(autorange='reversed'),
    width=1000,  # or any width you desire
    height=1000,  # or any height you desire
)

# Show the figure
pyo.iplot(fig)

In [59]:
X_train_tensor = torch.tensor(X_train_df.to_numpy(), dtype=torch.float, device=device)
y_train_tensor = torch.tensor(y_train, dtype=torch.float, device=device)

X_test_tensor = torch.tensor(X_test_df.to_numpy(), dtype=torch.float, device=device)
y_test_tensor = torch.tensor(y_test, dtype=torch.float, device=device)

train_data = RollingWindowDataset(X_train_tensor, y_train_tensor, window_size=time_step, device=device)
test_data = RollingWindowDataset(X_test_tensor, y_test_tensor, window_size=time_step, device=device)

print(test_data.__getitem__(0)[1])
print(test_data.__getitem__(1)[0])

tensor(0.7379, device='cuda:0')
tensor([[0.7245, 0.7886, 0.7977, 0.7520, 0.8162, 0.7932, 0.7932, 0.8132, 0.8351,
         0.8952, 0.8677, 0.5236, 0.4322, 0.4487, 0.5273, 0.3933],
        [0.6857, 0.7784, 0.7753, 0.7519, 0.8155, 0.7928, 0.7928, 0.8109, 0.8352,
         0.9073, 0.8879, 0.5230, 0.4490, 0.3797, 0.4563, 0.3599],
        [0.6617, 0.7874, 0.7901, 0.7523, 0.8138, 0.7921, 0.7921, 0.8104, 0.8361,
         0.9139, 0.9012, 0.5342, 0.4649, 0.4445, 0.4976, 0.3821],
        [0.6236, 0.7974, 0.7962, 0.7521, 0.8153, 0.7928, 0.7928, 0.8098, 0.8373,
         0.9235, 0.9113, 0.5474, 0.4805, 0.4671, 0.5145, 0.3912],
        [0.5981, 0.7914, 0.7760, 0.7537, 0.8163, 0.7941, 0.7941, 0.8092, 0.8374,
         0.9237, 0.9172, 0.5399, 0.4914, 0.4592, 0.4471, 0.3605],
        [0.5869, 0.7794, 0.7495, 0.7546, 0.8078, 0.7900, 0.7900, 0.8083, 0.8361,
         0.8756, 0.9035, 0.5112, 0.4936, 0.4080, 0.3677, 0.3216],
        [0.5854, 0.7650, 0.7287, 0.7521, 0.8019, 0.7857, 0.7857, 0.8063, 0.8339,
         0.7960, 0.8581, 0.4709, 0.4865, 0.3590, 0.3118, 0.2921],
        [0.6453, 0.7842, 0.7755, 0.7524, 0.8000, 0.7849, 0.7849, 0.8050, 0.8341,
         0.7774, 0.8059, 0.4782, 0.4824, 0.4654, 0.4544, 0.3639],
        [0.6088, 0.7965, 0.7774, 0.7533, 0.8016, 0.7861, 0.7861, 0.8043, 0.8344,
         0.7888, 0.7750, 0.4855, 0.4807, 0.5578, 0.4597, 0.3667],
        [0.5723, 0.7852, 0.7740, 0.7605, 0.8012, 0.7895, 0.7895, 0.8036, 0.8345,
         0.8188, 0.7831, 0.4882, 0.4800, 0.6035, 0.4490, 0.3617],
        [0.5827, 0.7733, 0.7659, 0.7687, 0.7993, 0.7924, 0.7924, 0.8030, 0.8343,
         0.7983, 0.7906, 0.4834, 0.4783, 0.5378, 0.4231, 0.3496],
        [0.5960, 0.7621, 0.7405, 0.7742, 0.7969, 0.7939, 0.7939, 0.8019, 0.8327,
         0.7377, 0.7723, 0.4583, 0.4714, 0.4486, 0.3463, 0.3124],
        [0.5765, 0.7501, 0.7271, 0.7765, 0.7958, 0.7944, 0.7944, 0.8003, 0.8305,
         0.6628, 0.7167, 0.4275, 0.4590, 0.4211, 0.3088, 0.2931],
        [0.5583, 0.7608, 0.7388, 0.7927, 0.7862, 0.7972, 0.7972, 0.7992, 0.8291,
         0.6220, 0.6538, 0.4137, 0.4460, 0.4535, 0.3519, 0.3121],
        [0.5622, 0.7477, 0.7354, 0.7881, 0.7872, 0.7955, 0.7955, 0.7992, 0.8275,
         0.6178, 0.6111, 0.4007, 0.4327, 0.5122, 0.3416, 0.3072],
        [0.5462, 0.7599, 0.7513, 0.7864, 0.7852, 0.7936, 0.7936, 0.8002, 0.8268,
         0.6636, 0.6114, 0.4045, 0.4229, 0.5364, 0.4019, 0.3333],
        [0.5764, 0.7761, 0.7580, 0.7854, 0.7842, 0.7926, 0.7926, 0.8007, 0.8264,
         0.7016, 0.6398, 0.4138, 0.4171, 0.5657, 0.4266, 0.3443],
        [0.5921, 0.7619, 0.7426, 0.7831, 0.7816, 0.7901, 0.7901, 0.8003, 0.8253,
         0.7177, 0.6754, 0.4089, 0.4114, 0.5461, 0.3718, 0.3205],
        [0.6206, 0.7448, 0.6968, 0.7701, 0.7853, 0.7857, 0.7857, 0.7988, 0.8220,
         0.6670, 0.6766, 0.3676, 0.3977, 0.4085, 0.2382, 0.2535],
        [0.6081, 0.7171, 0.6833, 0.7563, 0.7869, 0.7798, 0.7798, 0.7972, 0.8181,
         0.6070, 0.6429, 0.3250, 0.3771, 0.4402, 0.2052, 0.2347],
        [0.5959, 0.7034, 0.6687, 0.7415, 0.7876, 0.7730, 0.7730, 0.7961, 0.8136,
         0.5756, 0.5922, 0.2812, 0.3510, 0.3655, 0.1712, 0.2147],
        [0.5762, 0.6900, 0.6682, 0.7281, 0.7892, 0.7673, 0.7673, 0.7949, 0.8093,
         0.5907, 0.5650, 0.2486, 0.3227, 0.3484, 0.1700, 0.2140],
        [0.5879, 0.7049, 0.6897, 0.7227, 0.7841, 0.7620, 0.7620, 0.7944, 0.8063,
         0.6254, 0.5716, 0.2435, 0.2990, 0.3853, 0.2674, 0.2523],
        [0.5853, 0.6914, 0.6677, 0.7149, 0.7784, 0.7552, 0.7552, 0.7935, 0.8023,
         0.6347, 0.5927, 0.2238, 0.2756, 0.3520, 0.2091, 0.2214],
        [0.5572, 0.6804, 0.6652, 0.7066, 0.7750, 0.7494, 0.7494, 0.7919, 0.7984,
         0.6337, 0.6080, 0.2090, 0.2536, 0.3005, 0.2026, 0.2178],
        [0.5297, 0.6685, 0.6527, 0.6956, 0.7754, 0.7442, 0.7442, 0.7907, 0.7940,
         0.6029, 0.6000, 0.1900, 0.2318, 0.2520, 0.1704, 0.2003],
        [0.5433, 0.6538, 0.6255, 0.6795, 0.7799, 0.7388, 0.7388, 0.7882, 0.7885,
         0.5879, 0.5833, 0.1556, 0.2067, 0.1687, 0.1075, 0.1632],
        [0.5557, 0.6668, 0.6498, 0.6728, 0.7734, 0.7321, 0.7321, 0.7862, 0.7844,
         0.5958, 0.5698, 0.1525, 0.1859, 0.2481, 0.2212, 0.2082],
        [0.5256, 0.6801, 0.6520, 0.6687, 0.7647, 0.7255, 0.7255, 0.7841, 0.7806,
         0.6128, 0.5733, 0.1555, 0.1699, 0.3070, 0.2309, 0.2122],
        [0.5644, 0.6608, 0.6189, 0.6593, 0.7577, 0.7173, 0.7173, 0.7814, 0.7753,
         0.6174, 0.5839, 0.1339, 0.1523, 0.1158, 0.1491, 0.1668],
        [0.5617, 0.6761, 0.6277, 0.6536, 0.7491, 0.7100, 0.7100, 0.7783, 0.7707,
         0.6084, 0.5883, 0.1280, 0.1369, 0.1605, 0.1898, 0.1832],
        [0.5389, 0.6622, 0.6185, 0.6454, 0.7445, 0.7035, 0.7035, 0.7746, 0.7658,
         0.5885, 0.5796, 0.1197, 0.1227, 0.1768, 0.1673, 0.1708],
        [0.5646, 0.6773, 0.6499, 0.6428, 0.7391, 0.6994, 0.6994, 0.7712, 0.7627,
         0.6410, 0.5880, 0.1434, 0.1167, 0.3005, 0.3052, 0.2288],
        [0.5655, 0.6895, 0.6535, 0.6425, 0.7308, 0.6949, 0.6949, 0.7684, 0.7599,
         0.6945, 0.6188, 0.1686, 0.1175, 0.3813, 0.3198, 0.2353],
        [0.5445, 0.7006, 0.6575, 0.6433, 0.7222, 0.6908, 0.6908, 0.7663, 0.7575,
         0.7638, 0.6813, 0.1951, 0.1240, 0.3916, 0.3365, 0.2425],
        [0.5309, 0.7126, 0.6763, 0.6492, 0.7093, 0.6868, 0.6868, 0.7630, 0.7561,
         0.8140, 0.7430, 0.2347, 0.1381, 0.4185, 0.4132, 0.2767],
        [0.5074, 0.7002, 0.6758, 0.6595, 0.6915, 0.6825, 0.6825, 0.7600, 0.7548,
         0.8756, 0.8075, 0.2680, 0.1568, 0.4105, 0.4111, 0.2759],
        [0.4925, 0.7102, 0.6850, 0.6695, 0.6765, 0.6794, 0.6794, 0.7577, 0.7540,
         0.9451, 0.8721, 0.3040, 0.1797, 0.4830, 0.4490, 0.2927],
        [0.4790, 0.7212, 0.6930, 0.6699, 0.6757, 0.6792, 0.6792, 0.7563, 0.7536,
         0.9697, 0.9276, 0.3408, 0.2063, 0.3519, 0.4816, 0.3075],
        [0.4712, 0.7092, 0.6880, 0.6696, 0.6765, 0.6795, 0.6795, 0.7558, 0.7530,
         0.9536, 0.9554, 0.3670, 0.2334, 0.3087, 0.4586, 0.2993],
        [0.4465, 0.7192, 0.6884, 0.6689, 0.6791, 0.6805, 0.6805, 0.7554, 0.7524,
         0.9231, 0.9476, 0.3890, 0.2600, 0.3267, 0.4604, 0.3001],
        [0.4445, 0.7331, 0.7062, 0.6665, 0.6851, 0.6825, 0.6825, 0.7552, 0.7528,
         0.9317, 0.9341, 0.4219, 0.2886, 0.3368, 0.5376, 0.3335],
        [0.4810, 0.7472, 0.7283, 0.6614, 0.6937, 0.6846, 0.6846, 0.7554, 0.7542,
         0.9518, 0.9335, 0.4667, 0.3215, 0.3912, 0.6197, 0.3738],
        [0.4616, 0.7587, 0.7379, 0.6561, 0.7057, 0.6883, 0.6883, 0.7566, 0.7561,
         0.9821, 0.9545, 0.5099, 0.3575, 0.3851, 0.6520, 0.3910]],
       device='cuda:0')

# Vanilla LSTM

<img src="/home/arda/Turkcell/RNN/LSTM/images/Screenshot from 2024-01-29 15-02-08.png" alt="Alt text">

- the output of an LSTM at a particular point in time is dependant on three things: ▹ The current long-term memory of the network — known as the cell state ▹ The output at the previous point in time — known as the previous hidden state ▹ The input data at the current time step

- LSTMs use a series of 'gates' which control how the information in a sequence of data comes into, is stored in and leaves the network.

- the forget gate decides which pieces of the long-term memory should now be forgotten (have less weight) given the previous hidden state and the new data point in the sequence.

- The next step involves the new memory network and the input gate. The goal of this step is to determine what new information should be added to the networks long-term memory (cell state), given the previous hidden state and new input data.

- The new memory network is a tanh activated neural network which has learned how to combine the previous hidden state and new input data to generate a 'new memory update vector'.This vector tells us how much to update each component of the long-term memory (cell state) of the network given the new data.

- Note that we use a tanh here because its values lie in [-1,1] and so can be negative. The possibility of negative values here is necessary if we wish to reduce the impact of a component in the cell state.

- in part 1 above, where we generate the new memory vector, there is a big problem, it doesn't actually check if the new input data is even worth remembering. This is where the input gate comes in. The input gate is a sigmoid activated network which acts as a filter, identifying which components of the 'new memory vector' are worth retaining.

- the output gate, deciding the new hidden state. To decide this, we will use three things; the newly updated cell state, the previous hidden state and the new input data.

Note: The number of LSTM units in a layer corresponds to the dimensionality of the hidden state vector at each time step. If a layer has N LSTM units, the hidden state vector at each time step will be N-dimensional.

hidden state and current input multiply and sum sigmoid function formula

In [60]:
class VanillaLSTMModel(nn.Module):
    def __init__(self, input_dim, hidden_size, layer_size, output_dim, dropout_prob):
        super(VanillaLSTMModel, self).__init__()

        self.hidden_size = hidden_size
        self.layer_size = layer_size

        self.lstm = nn.LSTM(input_size = input_dim, hidden_size = self.hidden_size, num_layers=self.layer_size,
                            dropout=(dropout_prob if self.layer_size > 1 else 0), batch_first=True)
                            
        self.dropout = nn.Dropout(dropout_prob)
        
        self.fc = nn.Linear(self.hidden_size, output_dim)

    def forward(self, x):
        # Initializing hidden state
        h0 = torch.zeros(self.layer_size, x.size(0), self.hidden_size).to(device) 

        # Initialize cell state
        c0 = torch.zeros(self.layer_size, x.size(0), self.hidden_size).to(device) 

        # Forward propagate LSTM
        out, (hn, cn) = self.lstm(x, (h0.detach(), c0.detach()))

        out = self.dropout(out[:, -1, :])  # Add dropout

        out = self.fc(out)

        return out

In [62]:
class ModelActioner:
    
    def __init__(self, train_data, test_data, device):
        self.train_data = train_data
        self.test_data = test_data
        self.device = device
        self.model = None
        self.optimizer = None
        self.criterion = nn.MSELoss()

    
    def train_validate(self, config, trial):

        batch_size = config["batch_size"]
        epochs = config["epochs"]
        hidden_size = config["hidden_size"]
        num_layers = 1
        learning_rate = config["learning_rate"]
        dropout_prob = config["dropout_prob"]
        weight_decay = config["weight_decay"]
        lr_step_size = config["lr_step_size"]
        gamma = config["gamma"]

        self.model = VanillaLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, output_dim=1).to(self.device)

        n_splits = 5
        tscv = TimeSeriesSplit(n_splits=n_splits)

        val_losses = []

        for fold, (train_ids, val_ids) in enumerate(tscv.split(self.train_data)):
            print(f'Starting fold {fold+1}:')

            self.optimizer = optim.Adam(self.model.parameters(), lr = learning_rate, weight_decay=weight_decay)

            scheduler = ReduceLROnPlateau(self.optimizer, patience=lr_step_size, factor=gamma, mode="min", verbose=True) 

            train_subset = Subset(self.train_data, train_ids)
            val_subset = Subset(self.train_data, val_ids)
            
            # Creating data loader
            train_loader = DataLoader(dataset=train_subset, batch_size=batch_size, shuffle=False)
            val_loader = DataLoader(dataset=val_subset, batch_size=batch_size, shuffle=False)

            # Training Loop
            for epoch in range(epochs):
                print('epochs {}/{}'.format(epoch+1,epochs))

                running_loss = 0.0
                total_sample_train = 0

                self.model.train()

                for batch_idx, (data, target) in enumerate(train_loader):
                    data, target = data.to(self.device), target.to(self.device)
                    target = target.view(-1,1)


                    self.optimizer.zero_grad()
                    preds = self.model(data)

                    loss = self.criterion(preds, target)
                    loss.backward()
                    self.optimizer.step() # Update model params

                    running_loss += loss.item() * data.size(0)
                    total_sample_train += data.size(0)

                train_loss = running_loss/total_sample_train
                #print(f"train loss: {train_loss}")

                self.model.eval()
                val_running_loss = 0.0
                total_sample_val = 0

                with torch.no_grad():

                    for batch_idx, (data, target) in enumerate(val_loader):
                        data, target = data.to(self.device), target.to(self.device)
                        target = target.view(-1,1)

                        preds = self.model(data)
                        loss = self.criterion(preds, target)

                        val_running_loss += loss.item() * data.size(0)
                        total_sample_val += data.size(0)
                
                if trial.should_prune():
                    raise optuna.TrialPruned()
                
                val_loss = val_running_loss/total_sample_val
                val_losses.append(val_loss)
                scheduler.step(val_loss)
                
                unique_step = fold * epochs + epoch
                trial.report(val_loss, unique_step)

                current_lr = self.optimizer.param_groups[0]['lr']

                print(f'Current Learning Rate: {current_lr}')
                print(f"train_loss: {train_loss}, val_loss: {val_loss}")
                
        mean_val_loss = np.mean(val_losses)
        print(f"Mean validation loss: {mean_val_loss}")
        return mean_val_loss
    
                    
    def train(self, config):

        batch_size = config["batch_size"]
        epochs = config["epochs"]
        hidden_size = config["hidden_size"]
        num_layers = 1
        learning_rate = config["learning_rate"]
        dropout_prob = config["dropout_prob"]
        weight_decay = config["weight_decay"]
        lr_step_size = config["lr_step_size"]
        gamma = config["gamma"]

        self.model = VanillaLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, output_dim=1).to(self.device)

        # Update optimizer with updated lr
        self.optimizer = optim.Adam(self.model.parameters(), lr = learning_rate, weight_decay=weight_decay)

        # Creating data loader
        train_loader = DataLoader(dataset=self.train_data, batch_size=batch_size, shuffle=False)

        scheduler = ReduceLROnPlateau(self.optimizer, patience=lr_step_size, factor=gamma, mode="min", verbose=True)  

        # Training Loop
        for epoch in range(epochs):
            print('epochs {}/{}'.format(epoch+1,epochs))

            running_loss = 0.0
            total_sample_train = 0

            self.model.train()

            for batch_idx, (data, target) in enumerate(train_loader):

                data, target = data.to(self.device), target.to(self.device)
                target = target.view(-1,1)  

                self.optimizer.zero_grad()
                preds = self.model(data)

                loss = self.criterion(preds, target)
                #loss = loss.mean()
                loss.backward()
                self.optimizer.step() # Update model params

                running_loss += loss.item() * data.size(0)
                total_sample_train += data.size(0)

            train_loss = running_loss/total_sample_train
            #print(f"train loss: {train_loss}")
            scheduler.step(train_loss)
            current_lr = self.optimizer.param_groups[0]['lr']

            print(f'Current Learning Rate: {current_lr}')
            print(f"train_loss: {train_loss}")
        
        return self.model
            
    
    def test(self, config):
        batch_size = config["batch_size"]
        all_preds = []

        test_loader = DataLoader(dataset=self.test_data, batch_size=batch_size, shuffle=False)

        running_loss = .0
        total_sample = 0

        self.model.eval()

        with torch.no_grad():

            for batch_idx, (data, target) in enumerate(test_loader):

                data, target = data.to(self.device), target.to(self.device)
                target = target.view(-1,1)
                
                preds = self.model(data)
                loss = self.criterion(preds, target)

                running_loss += loss.item() * data.size(0)
                total_sample += data.size(0)

                all_preds.extend(preds.cpu().numpy())

            test_loss = running_loss/total_sample
            print(f"test_loss: {test_loss}")

        return all_preds

In [63]:

def objective(trial):
    config = {
        "batch_size": trial.suggest_int("batch_size", 32, 128, log=True),
        "epochs": trial.suggest_int("epochs", 50, 150),
        "hidden_size": trial.suggest_int("hidden_size", 10, 100),
        "learning_rate": trial.suggest_float("learning_rate", 1e-6, 1e-1, log=True),
        "dropout_prob": trial.suggest_float("dropout_prob", 0.0, 0.15),
        "weight_decay": trial.suggest_float("weight_decay", 1e-6, 1e-3, log=True),
        "lr_step_size": trial.suggest_int("lr_step_size", 10, 100), 
        "gamma": trial.suggest_float("gamma", 0.1, 0.9)
    }

    trainer = ModelActioner(train_data, test_data, device)

    val_loss = trainer.train_validate(config, trial)

    return val_loss

In [64]:
study_name = "Vanilla-LSTM-Tunner"
storage_url = "sqlite:///db.sqlite3"

optuna.delete_study(study_name=study_name, storage= storage_url)

study = optuna.create_study(direction='minimize', 
                            storage=storage_url, 
                            sampler=TPESampler(),
                            pruner=optuna.pruners.HyperbandPruner(
                            min_resource=30,  
                            max_resource=150,  
                            reduction_factor=3,  
                            ),
                            study_name=study_name,
                            load_if_exists=False)

pbar = tqdm(total=10, desc='Optimizing', unit='trial')

def callback(study, trial):
    # Update the progress bar
    pbar.update(1)
    pbar.set_postfix_str(f"Best Value: {study.best_value:.4f}")


study.optimize(objective, n_trials=10, callbacks=[callback])
pbar.close()

# Best hyperparameters
print('Number of finished trials:', len(study.trials))
print('Best trial:')
trial = study.best_trial

print('Value:', trial.value)
print('Params:')
for key, value in trial.params.items():
    print(f'{key}: {value}')

[I 2024-01-30 15:13:10,258] A new study created in RDB with name: Vanilla-LSTM-Tunner

Optimizing:   0%|          | 0/10 [00:00<?, ?trial/s]

Starting fold 1:
epochs 1/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.027789322610356305, val_loss: 0.0039938873803568265
epochs 2/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.00206311280980069, val_loss: 0.004354071892088368
epochs 3/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.0040147566837013555, val_loss: 0.003044894775720658
epochs 4/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.0021432883130680573, val_loss: 0.0005932987394136568
epochs 5/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.0004934209519935967, val_loss: 0.0020371779675346616
epochs 6/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.0014425492592731882, val_loss: 0.003328247929593085
epochs 7/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.002062427105173763, val_loss: 0.0028885440323772847
epochs 8/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.0015203989643946681, val_loss: 0.0016035687036087944
epochs 9/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.0006819991180428156, val_loss: 0.0007007889227544958
epochs 10/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.00028866520120860323, val_loss: 0.0004841007597783886
epochs 11/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.00032340618283916757, val_loss: 0.0004803383920468617
epochs 12/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.00032518941282576536, val_loss: 0.00046490586443469125
epochs 13/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.0002252179332763741, val_loss: 0.0006102344502261273
epochs 14/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.00020937892584601956, val_loss: 0.0008719406452087843
epochs 15/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.00028610095231622264, val_loss: 0.000988855168639766
epochs 16/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.0003014213940140938, val_loss: 0.0008633589385435843
epochs 17/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.00021715745836110343, val_loss: 0.0006413986681124057
epochs 18/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.00012964294786031947, val_loss: 0.0004968843252672789
epochs 19/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.00011776682367781177, val_loss: 0.00045568397905857414
epochs 20/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.00011894716168937616, val_loss: 0.0004865163698528829
epochs 21/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.00011076085329956473, val_loss: 0.0005732625724809989
epochs 22/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.00010871007811817292, val_loss: 0.0006479820103055634
epochs 23/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.00010970211224048398, val_loss: 0.0006431510193299911
epochs 24/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.00010080211799695941, val_loss: 0.000574286147076193
epochs 25/120
Current Learning Rate: 0.0012710346502279545
train_loss: 8.691245430351333e-05, val_loss: 0.0005118366837946244
epochs 26/120
Current Learning Rate: 0.0012710346502279545
train_loss: 8.741306431291282e-05, val_loss: 0.0004975552559477923
epochs 27/120
Current Learning Rate: 0.0012710346502279545
train_loss: 8.800970738919109e-05, val_loss: 0.0005268611207683866
epochs 28/120
Current Learning Rate: 0.0012710346502279545
train_loss: 8.139749154093136e-05, val_loss: 0.0005751520637194898
epochs 29/120
Current Learning Rate: 0.0012710346502279545
train_loss: 8.211083599905435e-05, val_loss: 0.0005984721675597712
epochs 30/120
Current Learning Rate: 0.0012710346502279545
train_loss: 8.796818177583383e-05, val_loss: 0.000575390456197537
epochs 31/120
Current Learning Rate: 0.0012710346502279545
train_loss: 8.328690359791692e-05, val_loss: 0.000541271168143284
epochs 32/120
Current Learning Rate: 0.0012710346502279545
train_loss: 7.129383984168893e-05, val_loss: 0.000531404326331405
epochs 33/120
Current Learning Rate: 0.0012710346502279545
train_loss: 7.295527010635277e-05, val_loss: 0.0005447194909922675
epochs 34/120
Current Learning Rate: 0.0012710346502279545
train_loss: 8.108075991530266e-05, val_loss: 0.0005710825891352244
epochs 35/120
Current Learning Rate: 0.0012710346502279545
train_loss: 7.95055472592235e-05, val_loss: 0.0005723026257886664
epochs 36/120
Current Learning Rate: 0.0012710346502279545
train_loss: 6.895587303963686e-05, val_loss: 0.0005647615134154283
epochs 37/120
Current Learning Rate: 0.0012710346502279545
train_loss: 7.122727516903787e-05, val_loss: 0.0005603453406442582
epochs 38/120
Current Learning Rate: 0.0012710346502279545
train_loss: 6.759814325625102e-05, val_loss: 0.0005676209805031287
epochs 39/120
Current Learning Rate: 0.0012710346502279545
train_loss: 7.697048433903164e-05, val_loss: 0.0005687303158867902
epochs 40/120
Current Learning Rate: 0.0012710346502279545
train_loss: 7.60588434212351e-05, val_loss: 0.0005598666602819566
epochs 41/120
Current Learning Rate: 0.0012710346502279545
train_loss: 6.856077590399716e-05, val_loss: 0.0005600198091419842
epochs 42/120
Current Learning Rate: 0.0012710346502279545
train_loss: 6.84773530290266e-05, val_loss: 0.000565732024066771
epochs 43/120
Current Learning Rate: 0.0012710346502279545
train_loss: 7.471094872208166e-05, val_loss: 0.000558236963539101
epochs 44/120
Current Learning Rate: 0.0012710346502279545
train_loss: 7.019826175804298e-05, val_loss: 0.0005471636334843145
epochs 45/120
Current Learning Rate: 0.0012710346502279545
train_loss: 6.968353045522235e-05, val_loss: 0.0005395124051901611
epochs 46/120
Current Learning Rate: 0.0012710346502279545
train_loss: 7.165882178876353e-05, val_loss: 0.0005524148725305202
epochs 47/120
Current Learning Rate: 0.0012710346502279545
train_loss: 7.009471990290637e-05, val_loss: 0.0005615766504893409
epochs 48/120
Current Learning Rate: 0.0012710346502279545
train_loss: 6.628598432718335e-05, val_loss: 0.0005522518615526635
epochs 49/120
Current Learning Rate: 0.0012710346502279545
train_loss: 6.475824729453674e-05, val_loss: 0.0005453050668750491
epochs 50/120
Current Learning Rate: 0.0012710346502279545
train_loss: 7.034297634259259e-05, val_loss: 0.0005433329572918376
epochs 51/120
Current Learning Rate: 0.0012710346502279545
train_loss: 6.963326162995624e-05, val_loss: 0.0005616766372763321
epochs 52/120
Current Learning Rate: 0.0012710346502279545
train_loss: 6.993540764118447e-05, val_loss: 0.0005622171495348787
epochs 53/120
Current Learning Rate: 0.0012710346502279545
train_loss: 6.884597831614021e-05, val_loss: 0.0005465554913537326
epochs 54/120
Current Learning Rate: 0.0012710346502279545
train_loss: 6.6331999014916e-05, val_loss: 0.0005334777961252257
epochs 55/120
Current Learning Rate: 0.0012710346502279545
train_loss: 6.562601725148085e-05, val_loss: 0.0005418881913693253
epochs 56/120
Current Learning Rate: 0.0012710346502279545
train_loss: 7.289580236446407e-05, val_loss: 0.000554900615406469
epochs 57/120
Current Learning Rate: 0.0012710346502279545
train_loss: 6.76260803486098e-05, val_loss: 0.0005554698595362001
epochs 58/120
Current Learning Rate: 0.0012710346502279545
train_loss: 6.362820261672728e-05, val_loss: 0.0005484006818656184
epochs 59/120
Current Learning Rate: 0.0012710346502279545
train_loss: 7.158635305945369e-05, val_loss: 0.0005474188011638555
epochs 60/120
Current Learning Rate: 0.0012710346502279545
train_loss: 6.936012256406492e-05, val_loss: 0.0005505413051294877
epochs 61/120
Current Learning Rate: 0.0012710346502279545
train_loss: 6.790631222860324e-05, val_loss: 0.0005594435955302928
epochs 62/120
Current Learning Rate: 0.0012710346502279545
train_loss: 6.446503252127993e-05, val_loss: 0.0005462854760240088
epochs 63/120
Current Learning Rate: 0.0012710346502279545
train_loss: 7.27798406411526e-05, val_loss: 0.0005291517219221634
epochs 64/120
Current Learning Rate: 0.0012710346502279545
train_loss: 6.865782205223743e-05, val_loss: 0.0005290980107645583
epochs 65/120
Current Learning Rate: 0.0012710346502279545
train_loss: 7.055222982001539e-05, val_loss: 0.0005436407496629741
epochs 66/120
Epoch 00066: reducing learning rate of group 0 to 6.3243e-04.
Current Learning Rate: 0.0006324292609184651
train_loss: 7.102419457576041e-05, val_loss: 0.0005737949682355898
epochs 67/120
Current Learning Rate: 0.0006324292609184651
train_loss: 6.392613163610037e-05, val_loss: 0.000571435010113024
epochs 68/120
Current Learning Rate: 0.0006324292609184651
train_loss: 6.826146148485255e-05, val_loss: 0.0005431418230054314
epochs 69/120
Current Learning Rate: 0.0006324292609184651
train_loss: 6.377895873524004e-05, val_loss: 0.0005255684009556062
epochs 70/120
Current Learning Rate: 0.0006324292609184651
train_loss: 6.599245841100223e-05, val_loss: 0.0005285782528478805
epochs 71/120
Current Learning Rate: 0.0006324292609184651
train_loss: 6.441246698255112e-05, val_loss: 0.000546678212274509
epochs 72/120
Current Learning Rate: 0.0006324292609184651
train_loss: 6.405770316058279e-05, val_loss: 0.0005675071605423308
epochs 73/120
Current Learning Rate: 0.0006324292609184651
train_loss: 6.737219710454443e-05, val_loss: 0.0005665078720927273
epochs 74/120
Current Learning Rate: 0.0006324292609184651
train_loss: 6.28279423452975e-05, val_loss: 0.0005509744796895166
epochs 75/120
Current Learning Rate: 0.0006324292609184651
train_loss: 6.316317462494083e-05, val_loss: 0.0005375225922396461
epochs 76/120
Current Learning Rate: 0.0006324292609184651
train_loss: 6.612134797921356e-05, val_loss: 0.0005398108362911329
epochs 77/120
Current Learning Rate: 0.0006324292609184651
train_loss: 6.662651216366182e-05, val_loss: 0.000542645504836439
epochs 78/120
Current Learning Rate: 0.0006324292609184651
train_loss: 6.213514911666464e-05, val_loss: 0.0005416884613666861
epochs 79/120
Current Learning Rate: 0.0006324292609184651
train_loss: 6.772557906898376e-05, val_loss: 0.0005377253416107066
epochs 80/120
Current Learning Rate: 0.0006324292609184651
train_loss: 6.796752016893343e-05, val_loss: 0.0005357423376861132
epochs 81/120
Current Learning Rate: 0.0006324292609184651
train_loss: 6.263985931965228e-05, val_loss: 0.0005372736318758812
epochs 82/120
Current Learning Rate: 0.0006324292609184651
train_loss: 6.344232985467993e-05, val_loss: 0.0005428470109811758
epochs 83/120
Current Learning Rate: 0.0006324292609184651
train_loss: 6.433710778334276e-05, val_loss: 0.0005529453502810885
epochs 84/120
Current Learning Rate: 0.0006324292609184651
train_loss: 6.286670797731188e-05, val_loss: 0.0005522589645811687
epochs 85/120
Current Learning Rate: 0.0006324292609184651
train_loss: 6.411348802334702e-05, val_loss: 0.0005495927549351041
epochs 86/120
Current Learning Rate: 0.0006324292609184651
train_loss: 6.623543863258276e-05, val_loss: 0.0005474033899156859
epochs 87/120
Current Learning Rate: 0.0006324292609184651
train_loss: 6.40869280974393e-05, val_loss: 0.0005450743045667113
epochs 88/120
Current Learning Rate: 0.0006324292609184651
train_loss: 6.278184609025055e-05, val_loss: 0.0005482655624820846
epochs 89/120
Current Learning Rate: 0.0006324292609184651
train_loss: 6.279321946510065e-05, val_loss: 0.0005574200955889725
epochs 90/120
Current Learning Rate: 0.0006324292609184651
train_loss: 6.1003987579361386e-05, val_loss: 0.0005572621598802802
epochs 91/120
Current Learning Rate: 0.0006324292609184651
train_loss: 6.537534720432871e-05, val_loss: 0.0005482281465822506
epochs 92/120
Current Learning Rate: 0.0006324292609184651
train_loss: 5.975438149394713e-05, val_loss: 0.0005414110212494427
epochs 93/120
Current Learning Rate: 0.0006324292609184651
train_loss: 6.54017663021621e-05, val_loss: 0.0005469069328105506
epochs 94/120
Current Learning Rate: 0.0006324292609184651
train_loss: 6.208844062807897e-05, val_loss: 0.0005494125844004057
epochs 95/120
Current Learning Rate: 0.0006324292609184651
train_loss: 7.191554610280467e-05, val_loss: 0.000542215328817884
epochs 96/120
Current Learning Rate: 0.0006324292609184651
train_loss: 5.959264834880167e-05, val_loss: 0.000535350010544616
epochs 97/120
Current Learning Rate: 0.0006324292609184651
train_loss: 6.764281868910123e-05, val_loss: 0.0005368935178719565
epochs 98/120
Current Learning Rate: 0.0006324292609184651
train_loss: 7.162153269746341e-05, val_loss: 0.0005468795640457535
epochs 99/120
Current Learning Rate: 0.0006324292609184651
train_loss: 7.267604182982866e-05, val_loss: 0.000538473809438218
epochs 100/120
Current Learning Rate: 0.0006324292609184651
train_loss: 6.890966831537968e-05, val_loss: 0.0005410999522335636
epochs 101/120
Current Learning Rate: 0.0006324292609184651
train_loss: 6.796291927457787e-05, val_loss: 0.0005430516490984397
epochs 102/120
Current Learning Rate: 0.0006324292609184651
train_loss: 6.754232249238014e-05, val_loss: 0.0005428416126055973
epochs 103/120
Current Learning Rate: 0.0006324292609184651
train_loss: 6.84035102925631e-05, val_loss: 0.0005504522952987201
epochs 104/120
Current Learning Rate: 0.0006324292609184651
train_loss: 7.582257910000503e-05, val_loss: 0.0005474418999809555
epochs 105/120
Current Learning Rate: 0.0006324292609184651
train_loss: 6.470557232923487e-05, val_loss: 0.0005310856415437431
epochs 106/120
Current Learning Rate: 0.0006324292609184651
train_loss: 6.24192009701418e-05, val_loss: 0.0005227087100840879
epochs 107/120
Current Learning Rate: 0.0006324292609184651
train_loss: 6.493098905928874e-05, val_loss: 0.0005347809415383304
epochs 108/120
Current Learning Rate: 0.0006324292609184651
train_loss: 6.294305594086549e-05, val_loss: 0.0005524391671454795
epochs 109/120
Current Learning Rate: 0.0006324292609184651
train_loss: 6.1022485074078614e-05, val_loss: 0.0005678643747593188
epochs 110/120
Current Learning Rate: 0.0006324292609184651
train_loss: 6.593753967440295e-05, val_loss: 0.0005552820348865772
epochs 111/120
Current Learning Rate: 0.0006324292609184651
train_loss: 6.908581197326145e-05, val_loss: 0.0005257647082553905
epochs 112/120
Current Learning Rate: 0.0006324292609184651
train_loss: 7.1421459563824e-05, val_loss: 0.0005101022481790216
epochs 113/120
Epoch 00113: reducing learning rate of group 0 to 3.1468e-04.
Current Learning Rate: 0.00031467810102119855
train_loss: 6.602220348309187e-05, val_loss: 0.0005284890186943351
epochs 114/120
Current Learning Rate: 0.00031467810102119855
train_loss: 6.608919628840675e-05, val_loss: 0.0005365595967670848
epochs 115/120
Current Learning Rate: 0.00031467810102119855
train_loss: 6.741523554266773e-05, val_loss: 0.0005468358291884658
epochs 116/120
Current Learning Rate: 0.00031467810102119855
train_loss: 6.033439728382387e-05, val_loss: 0.0005537290476409167
epochs 117/120
Current Learning Rate: 0.00031467810102119855
train_loss: 7.132247054342817e-05, val_loss: 0.0005500066113657018
epochs 118/120
Current Learning Rate: 0.00031467810102119855
train_loss: 6.456023469294642e-05, val_loss: 0.0005470597553689023
epochs 119/120
Current Learning Rate: 0.00031467810102119855
train_loss: 5.994962702970952e-05, val_loss: 0.0005483181173013888
epochs 120/120
Current Learning Rate: 0.00031467810102119855
train_loss: 6.671964959088272e-05, val_loss: 0.0005528775899037818
Starting fold 2:
epochs 1/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.0003957435715848968, val_loss: 0.0033803759081161055
epochs 2/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.0015936557389826496, val_loss: 0.020038054073377262
epochs 3/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.00022030117681405402, val_loss: 0.007568853861090565
epochs 4/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.0007343362198020196, val_loss: 0.009153153739928727
epochs 5/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.00039852488534337666, val_loss: 0.01271525972458736
epochs 6/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.00015743676198143905, val_loss: 0.007392589217199693
epochs 7/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.00032037526453872233, val_loss: 0.006827840078301807
epochs 8/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.00025354410193557665, val_loss: 0.007867812378598111
epochs 9/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.000149738675268738, val_loss: 0.00528792427943911
epochs 10/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.00022032837906626906, val_loss: 0.0050195577910426194
epochs 11/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.00018441037776803788, val_loss: 0.005033418764705183
epochs 12/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.00015344153966439524, val_loss: 0.003996266660689519
epochs 13/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.00017444177223234326, val_loss: 0.003982597852997955
epochs 14/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.00015431256388255093, val_loss: 0.0036485047253937753
epochs 15/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.00014694114196090282, val_loss: 0.003475059361859821
epochs 16/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.00014179980006891532, val_loss: 0.003328914270876715
epochs 17/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.0001411463724053649, val_loss: 0.0030249786403377557
epochs 18/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.00013948109177233637, val_loss: 0.0030854660654243415
epochs 19/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.00012262278840180466, val_loss: 0.0027719143563733686
epochs 20/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.00012837616250036888, val_loss: 0.0027688813179290346
epochs 21/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.00011817497032477047, val_loss: 0.002608197057809405
epochs 22/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.00011915360528411771, val_loss: 0.002652952715165657
epochs 23/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.00011304756995468058, val_loss: 0.0025037226860630743
epochs 24/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.00010591762673784303, val_loss: 0.002512895789030673
epochs 25/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.00010619716388437563, val_loss: 0.0024438888250625933
epochs 26/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.00010411110766332456, val_loss: 0.002373766373946435
epochs 27/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.00010362055377959763, val_loss: 0.002280710527898803
epochs 28/120
Current Learning Rate: 0.0012710346502279545
train_loss: 0.00010154833864727202, val_loss: 0.002249447324112422
epochs 29/120
Current Learning Rate: 0.0012710346502279545
train_loss: 9.670728508651498e-05, val_loss: 0.002203162147284106
epochs 30/120
Current Learning Rate: 0.0012710346502279545
train_loss: 9.11826748704405e-05, val_loss: 0.0021579845773952978
epochs 31/120
Current Learning Rate: 0.0012710346502279545
train_loss: 9.025073811093328e-05, val_loss: 0.0022058322246213537
epochs 32/120
Current Learning Rate: 0.0012710346502279545
train_loss: 8.609049309166099e-05, val_loss: 0.002133284302775763
epochs 33/120
Current Learning Rate: 0.0012710346502279545
train_loss: 9.153330197201803e-05, val_loss: 0.0020577271583504856
epochs 34/120
Current Learning Rate: 0.0012710346502279545
train_loss: 8.856654050644785e-05, val_loss: 0.0021054829626649656
epochs 35/120
Current Learning Rate: 0.0012710346502279545
train_loss: 8.555078784891251e-05, val_loss: 0.0020259505746979757
epochs 36/120
Current Learning Rate: 0.0012710346502279545
train_loss: 8.324386429033638e-05, val_loss: 0.0018933720135397311
epochs 37/120
Current Learning Rate: 0.0012710346502279545
train_loss: 8.570049631137199e-05, val_loss: 0.0019708160928785605
epochs 38/120
Current Learning Rate: 0.0012710346502279545

[W 2024-01-30 15:13:40,423] Trial 0 failed with parameters: {'batch_size': 85, 'epochs': 120, 'hidden_size': 100, 'learning_rate': 0.0012710346502279545, 'dropout_prob': 0.004947180695087927, 'weight_decay': 0.00011223925718658074, 'lr_step_size': 46, 'gamma': 0.49757043272191026} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "/home/arda/anaconda3/lib/python3.11/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/tmp/ipykernel_55296/3393379696.py", line 15, in objective
    val_loss = trainer.train_validate(config, trial)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ipykernel_55296/2043730651.py", line 82, in train_validate
    preds = self.model(data)
            ^^^^^^^^^^^^^^^^
  File "/home/arda/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arda/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ipykernel_55296/3646311178.py", line 23, in forward
    out, (hn, cn) = self.lstm(x, (h0.detach(), c0.detach()))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arda/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arda/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arda/anaconda3/lib/python3.11/site-packages/torch/nn/modules/rnn.py", line 875, in forward
    self.check_forward_args(input, hx, batch_sizes)
  File "/home/arda/anaconda3/lib/python3.11/site-packages/torch/nn/modules/rnn.py", line 791, in check_forward_args
    self.check_hidden_size(hidden[0], self.get_expected_hidden_size(input, batch_sizes),
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arda/anaconda3/lib/python3.11/site-packages/torch/nn/modules/rnn.py", line 239, in get_expected_hidden_size
    def get_expected_hidden_size(self, input: Tensor, batch_sizes: Optional[Tensor]) -> Tuple[int, int, int]:

KeyboardInterrupt
[W 2024-01-30 15:13:40,426] Trial 0 failed with value None.

KeyboardInterrupt:

In [ ]:
trainer = ModelActioner(train_data, test_data, device)
model = trainer.train(trial.params)

epochs 1/79

Current Learning Rate: 0.00022078935295972353
train_loss: 0.42712533657771373
epochs 2/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.3398248373805689
epochs 3/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.23089723345548702
epochs 4/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.07332626369531525
epochs 5/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.07636017390744276
epochs 6/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.05740143414668837
epochs 7/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.03519123312709484
epochs 8/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.022575530587871956
epochs 9/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.012931673994312465
epochs 10/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0075616575059550715
epochs 11/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.007493208540759423
epochs 12/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.006598943400520848
epochs 13/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0065511049066838455
epochs 14/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.006808368317241317
epochs 15/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.006151008422564436
epochs 16/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.006518086873093365
epochs 17/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005963322841090515
epochs 18/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005801536664694942
epochs 19/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005900396936314616
epochs 20/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005933429457920107
epochs 21/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005832487656755397
epochs 22/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.006089632586054996
epochs 23/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005597768408874058
epochs 24/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005688919146270348
epochs 25/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005610412602735445
epochs 26/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0054901960593061565
epochs 27/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005685053858700893
epochs 28/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005556699224965163
epochs 29/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0052570857706639735
epochs 30/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005119805763545343
epochs 31/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005579564736803198
epochs 32/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00522636233045338
epochs 33/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005953478804145353
epochs 34/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005921007672095023
epochs 35/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005709554559227063
epochs 36/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005447982252874958
epochs 37/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.007055010963723654
epochs 38/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005473930816502528
epochs 39/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00529940725501118
epochs 40/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005362264869431042
epochs 41/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005345638763233363
epochs 42/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.004738838226013378
epochs 43/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.004826552458599801
epochs 44/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0047200813715136914
epochs 45/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005108330166787894
epochs 46/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0046174542674803
epochs 47/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.004648141056249977
epochs 48/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005248996516533754
epochs 49/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005266730245900246
epochs 50/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0049603048180709985
epochs 51/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.004315629417060296
epochs 52/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005204918489089884
epochs 53/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.004872833285070464
epochs 54/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00490208308659658
epochs 55/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0053712015823842675
epochs 56/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005509660719988236
epochs 57/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005553080757981421
epochs 58/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0050178782495419755
epochs 59/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0052773590107337625
epochs 60/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005501614485576027
epochs 61/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0050934451154232155
epochs 62/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.004904136323936218
epochs 63/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005850167727376856
epochs 64/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005719756424459855
epochs 65/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.006609382697418004
epochs 66/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005246741663857408
epochs 67/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005227128663284925
epochs 68/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005370037526811272
epochs 69/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0042065985950062845
epochs 70/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.004135298536011399
epochs 71/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.004343874537948076
epochs 72/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.004219933823653648
epochs 73/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0038714786478634185
epochs 74/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0038384543953356763
epochs 75/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0038255339158116326
epochs 76/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.004367548434088409
epochs 77/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.003851193078846921
epochs 78/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.004403466994911104
epochs 79/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0040497595308931125

In [ ]:
preds = trainer.test(trial.params)
preds = np.array(preds)

y_true = y_test[time_step:]
y_true = scaler_adj.inverse_transform(y_true.reshape(-1, 1)).flatten()
preds = scaler_adj.inverse_transform(preds.reshape(-1, 1)).flatten()


mse = mean_squared_error(y_true, preds)
print(f'Mean Squared Error: {mse:.4f}')

rmse = mean_squared_error(y_true, preds, squared=False)
print(f'Root Mean Squared Error: {rmse:.4f}')

r2 = r2_score(y_true, preds)
print(f'R² Score: {r2:.4f}')

mape = mean_absolute_percentage_error(y_true, preds)*100
print(f'mape Score: % {mape:.4f}')

test_loss: 0.0018684213240797896
Mean Squared Error: 39.7373
Root Mean Squared Error: 6.3038
R² Score: 0.8153
mape Score: % 3.0146

In [ ]:
stock_price = stock_data["Adj Close"].iloc[test_index:]
stock_price=stock_price.reset_index()
stock_price=stock_price.drop(columns=["index"])
stock_price

      Adj Close
0    140.325653
1    141.737747
2    141.071472
3    143.159805
4    145.118851
..          ...
247  182.679993
248  188.630005
249  191.559998
250  193.889999
251  195.179993

[252 rows x 1 columns]

In [ ]:
signals = pd.DataFrame(preds, columns=['pred'])
signals["next_day"] = pd.DataFrame(y_true)
signals["today"] = stock_price
signals["Signal_Pred"] = (signals["today"] < signals["pred"]).astype(int)
signals["Signal_True"] = (signals["today"] < signals["next_day"]).astype(int)

signals.head(50)

          pred    next_day       today  Signal_Pred  Signal_True
0   140.881531  141.737747  140.325653            1            1
1   142.025452  141.071472  141.737747            1            0
2   143.215378  143.159805  141.071472            1            1
3   144.477158  145.118851  143.159805            1            1
4   145.809738  142.205154  145.118851            1            0
5   147.055481  143.487961  142.205154            1            1
6   148.211044  144.621628  143.487961            1            1
7   149.317261  149.981674  144.621628            1            1
8   150.518585  153.641220  149.981674            1            1
9   151.864792  150.886612  153.641220            0            0
10  153.201096  153.790375  150.886612            1            1
11  154.531586  151.075562  153.790375            1            0
12  155.742294  150.031387  151.075562            1            0
13  156.790314  150.399902  150.031387            1            1
14  157.679916  153.228439  150.399902            1            1
15  158.488434  152.581055  153.228439            1            0
16  159.216721  154.702438  152.581055            1            1
17  159.934814  153.089005  154.702438            1            0
18  160.596390  151.933685  153.089005            1            0
19  161.171127  147.880127  151.933685            1            0
20  161.546509  148.308395  147.880127            1            1
21  161.708405  148.796417  148.308395            1            1
22  161.668320  146.117294  148.796417            1            0
23  161.364059  147.322372  146.117294            1            1
24  160.883804  146.814438  147.322372            1            0
25  160.287659  144.722916  146.814438            1            0
26  159.578186  145.320511  144.722916            1            1
27  158.833847  150.419815  145.320511            1            1
28  158.280579  153.208511  150.419815            1            1
29  158.047470  150.987534  153.208511            1            0
30  158.065643  152.252396  150.987534            1            1
31  158.322617  149.981598  152.252396            1            0
32  158.658600  147.900040  149.981598            1            0
33  158.933517  149.862076  147.900040            1            1
34  159.146957  151.973526  149.862076            1            1
35  159.354874  152.371902  151.973526            1            1
36  159.595047  155.220352  152.371902            1            1
37  159.957275  154.373779  155.220352            1            0
38  160.401581  156.764084  154.373779            1            1
39  160.968460  158.636490  156.764084            1            1
40  161.661224  157.192352  158.636490            1            0
41  162.379410  158.287903  157.192352            1            1
42  163.095764  159.602570  158.287903            1            1
43  163.793152  157.640533  159.602570            1            0
44  164.389938  157.013077  157.640533            1            0
45  164.861588  160.120483  157.013077            1            1
46  165.313766  161.704041  160.120483            1            1
47  165.809326  164.233780  161.704041            1            1
48  166.413712  165.498672  164.233780            1            1
49  167.138184  164.960831  165.498672            1            0

In [ ]:
signals["Signal_Pred"].value_counts()

Signal_Pred
0    127
1    124
Name: count, dtype: int64

In [ ]:
signals["Date"] = date_test
signals

           pred    next_day       today  Signal_Pred  Signal_True       Date
0    140.881531  141.737747  140.325653            1            1 2023-01-23
1    142.025452  141.071472  141.737747            1            0 2023-01-24
2    143.215378  143.159805  141.071472            1            1 2023-01-25
3    144.477158  145.118851  143.159805            1            1 2023-01-26
4    145.809738  142.205154  145.118851            1            0 2023-01-27
..          ...         ...         ...          ...          ...        ...
246  180.227432  182.679993  183.630005            0            0 2024-01-16
247  179.823166  188.630005  182.679993            0            1 2024-01-17
248  179.591934  191.559998  188.630005            0            1 2024-01-18
249  179.598038  193.889999  191.559998            0            1 2024-01-19
250  179.876053  195.179993  193.889999            0            1 2024-01-22

[251 rows x 6 columns]

In [ ]:
stock_price = stock_data["Adj Close"].iloc[test_index:]
stock_price=stock_price.reset_index()
stock_price=stock_price.drop(columns=["index"])
stock_price

      Adj Close
0    140.325653
1    141.737747
2    141.071472
3    143.159805
4    145.118851
..          ...
247  182.679993
248  188.630005
249  191.559998
250  193.889999
251  195.179993

[252 rows x 1 columns]

In [ ]:
date_test["Date"] = date_test["Date"].dt.strftime('%Y-%m-%d')
date_test

           Date
0    2023-01-23
1    2023-01-24
2    2023-01-25
3    2023-01-26
4    2023-01-27
..          ...
247  2024-01-17
248  2024-01-18
249  2024-01-19
250  2024-01-22
251  2024-01-23

[252 rows x 1 columns]

In [ ]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=np.array(date_test).flatten(), y=stock_data["Adj Close"].iloc[test_index:], mode='lines', name='TSLA Stock Price'))

# Buy and sell signals
buy_signals = signals[signals['Signal_Pred'] == 1]
sell_signals = signals[signals['Signal_Pred'] == 0]

# Ensure that buy and sell prices are aligned with the signals by matching on the 'Date' column
buy_prices = stock_data[stock_data['Date'].isin(buy_signals['Date'])]["Adj Close"]
sell_prices = stock_data[stock_data['Date'].isin(sell_signals['Date'])]["Adj Close"]


# Plot buy signals
fig.add_trace(go.Scatter(
    x=buy_signals['Date'], 
    y=buy_prices, 
    mode='markers', 
    name='Buy', 
    marker=dict(color='green', size=10, symbol='triangle-up')
))


# Plot sell signals
fig.add_trace(go.Scatter(
    x=sell_signals['Date'], 
    y=sell_prices, 
    mode='markers', 
    name='Sell', 
    marker=dict(color='red', size=10, symbol='triangle-down')
))


# Update layout
fig.update_layout(
    title='Stock Price with Buy and Sell Signals',
    xaxis_title='Date',
    yaxis_title='Price',
    xaxis_rangeslider_visible=False,
    height = 700,
    width=1280
)

# Show the plot
pyo.iplot(fig)

/home/arda/anaconda3/lib/python3.11/site-packages/_plotly_utils/basevalidators.py:106: FutureWarning:

The behavior of DatetimeProperties.to_pydatetime is deprecated, in a future version this will return a Series containing python datetime objects instead of an ndarray. To retain the old behavior, call `np.array` on the result

In [ ]:
trace_pred = go.Scatter(
    x=np.array(date_test).flatten(),
    y=signals['pred'],
    mode='lines+markers',
    name='Predicted'
)

trace_true = go.Scatter(
    x=np.array(date_test).flatten(),
    y=signals['next_day'],
    mode='lines+markers',
    name='Actual Next Day'
)

# Define the layout
layout = go.Layout(
    title='Predicted vs Actual Next Day Values',
    xaxis=dict(title='Index'),
    yaxis=dict(title='Value'),
    height=700
)

# Create the figure and add traces
fig = go.Figure(data=[trace_pred, trace_true], layout=layout)

# Show the figure
fig.show()